export type CapitalMode='fixed'|'compounding'|'sequential';
export type HistoricalBacktestTrade={signalId:string;symbol:string;instrumentKey:string;side:'BUY'|'SELL';date:string;entryTime:string;exitTime:string;entryPrice:number;exitPrice:number;stopLoss:number;exitReason:string;intradayMarginPercent:number;intradayLeverage:number};
export type SimulatedTrade=HistoricalBacktestTrade&{quantity:number;leverage:number;positionValue:number;marginRequired:number;grossPnl:number;brokerage:number;stt:number;exchangeCharges:number;gst:number;sebiCharges:number;stampDuty:number;taxes:number;slippage:number;totalCharges:number;netPnl:number;capitalBefore:number;capitalAfter:number};
export type DailySimulation={date:string;trades:number;capitalUsed:number;peakMarginUsed:number;capitalTurnover:number;notionalTurnover:number;grossProfit:number;grossLoss:number;brokerage:number;taxes:number;slippage:number;netProfit:number};
export type CapitalSimulation={startingCapital:number;capitalPerTrade:number;capitalMode:CapitalMode;totalTrades:number;winningTrades:number;losingTrades:number;excludedTrades:number;totalCapitalUsed:number;peakMarginUsed:number;capitalTurnover:number;notionalTurnover:number;grossProfit:number;grossLoss:number;brokeragePaid:number;taxesPaid:number;slippageCost:number;totalCharges:number;netProfit:number;endingCapital:number;roi:number;profitFactor:number;maximumDrawdown:number;averageProfitPerTrade:number;averageLossPerTrade:number;bestDay:DailySimulation|null;worstDay:DailySimulation|null;maximumDailyProfit:number;maximumDailyLoss:number;daily:DailySimulation[];trades:SimulatedTrade[]};
const STT_SELL=.00025,NSE_TRANSACTION=.0000297,SEBI_TURNOVER=.000001,STAMP_BUY=.00003,GST=.18;
export function simulateHistoricalTrades(source:HistoricalBacktestTrade[],startingCapital:number,brokeragePerTrade:number,slippagePercent:number,riskPercent=1,capitalMode:CapitalMode='fixed'):CapitalSimulation{
 const start=Math.max(1_000,Math.min(10_000_000,Number(startingCapital)||0)),brokerage=Math.max(0,Number(brokeragePerTrade)||0),slippageRate=Math.max(0,Number(slippagePercent)||0)/100,riskRate=Math.max(.1,Math.min(100,Number(riskPercent)||1))/100;
 let balance=start,excludedTrades=0;const rows:SimulatedTrade[]=[];
 for(const trade of [...source].sort((a,b)=>new Date(a.entryTime||a.date).getTime()-new Date(b.entryTime||b.date).getTime())){
  const entry=Number(trade.entryPrice),exit=Number(trade.exitPrice),stop=Number(trade.stopLoss),marginPercent=Number(trade.intradayMarginPercent),providedLeverage=Number(trade.intradayLeverage),marginRate=marginPercent>0?marginPercent/100:providedLeverage>0?1/providedLeverage:0;
  if(!(entry>0)||!(exit>0)||!(stop>0)||!(marginRate>0)){excludedTrades++;continue;}
  const allocation=capitalMode==='fixed'?start:Math.max(0,balance),riskPerShare=Math.abs(entry-stop),quantityByMargin=Math.floor(allocation/(entry*marginRate)),quantityByRisk=riskPerShare>0?Math.floor(allocation*riskRate/riskPerShare):0,quantity=Math.max(0,Math.min(quantityByMargin,quantityByRisk));
  if(!quantity){excludedTrades++;continue;}
  const buyPrice=trade.side==='BUY'?entry:exit,sellPrice=trade.side==='BUY'?exit:entry,buyTurnover=buyPrice*quantity,sellTurnover=sellPrice*quantity,turnover=buyTurnover+sellTurnover,positionValue=entry*quantity,marginRequired=positionValue*marginRate,grossPnl=(trade.side==='BUY'?exit-entry:entry-exit)*quantity;
  const exchangeCharges=turnover*NSE_TRANSACTION,sebiCharges=turnover*SEBI_TURNOVER,stt=sellTurnover*STT_SELL,stampDuty=buyTurnover*STAMP_BUY,gst=(brokerage+exchangeCharges+sebiCharges)*GST,taxes=stt+exchangeCharges+sebiCharges+stampDuty+gst,slippage=turnover*slippageRate,totalCharges=brokerage+taxes+slippage,netPnl=grossPnl-totalCharges,capitalBefore=balance,capitalAfter=balance+netPnl;
  rows.push({...trade,quantity,leverage:1/marginRate,positionValue,marginRequired,grossPnl,brokerage,stt,exchangeCharges,gst,sebiCharges,stampDuty,taxes,slippage,totalCharges,netPnl,capitalBefore,capitalAfter});balance=capitalAfter;
 }
 const dailyMap=new Map<string,DailySimulation>();for(const row of rows){const date=new Date(row.exitTime||row.date).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}),day=dailyMap.get(date)??{date,trades:0,capitalUsed:0,peakMarginUsed:0,capitalTurnover:0,notionalTurnover:0,grossProfit:0,grossLoss:0,brokerage:0,taxes:0,slippage:0,netProfit:0};day.trades++;day.peakMarginUsed=Math.max(day.peakMarginUsed,row.marginRequired);day.capitalUsed=day.peakMarginUsed;day.capitalTurnover+=row.marginRequired;day.notionalTurnover+=row.positionValue;day.grossProfit+=Math.max(0,row.grossPnl);day.grossLoss+=Math.abs(Math.min(0,row.grossPnl));day.brokerage+=row.brokerage;day.taxes+=row.taxes;day.slippage+=row.slippage;day.netProfit+=row.netPnl;dailyMap.set(date,day);}
 const daily=[...dailyMap.values()].sort((a,b)=>a.date.localeCompare(b.date)),sum=(v:number[])=>v.reduce((a,b)=>a+b,0),wins=rows.filter(r=>r.netPnl>0),losses=rows.filter(r=>r.netPnl<0),grossProfit=sum(rows.map(r=>Math.max(0,r.grossPnl))),grossLoss=sum(rows.map(r=>Math.abs(Math.min(0,r.grossPnl)))),netWinning=sum(wins.map(r=>r.netPnl)),netLosing=Math.abs(sum(losses.map(r=>r.netPnl))),netProfit=sum(rows.map(r=>r.netPnl));let equity=0,peak=0,maximumDrawdown=0;for(const row of rows){equity+=row.netPnl;peak=Math.max(peak,equity);maximumDrawdown=Math.max(maximumDrawdown,peak-equity);}const bestDay=daily.length?[...daily].sort((a,b)=>b.netProfit-a.netProfit)[0]:null,worstDay=daily.length?[...daily].sort((a,b)=>a.netProfit-b.netProfit)[0]:null,peakMarginUsed=Math.max(0,...rows.map(r=>r.marginRequired));
 return{startingCapital:start,capitalPerTrade:start,capitalMode,totalTrades:rows.length,winningTrades:wins.length,losingTrades:losses.length,excludedTrades,totalCapitalUsed:peakMarginUsed,peakMarginUsed,capitalTurnover:sum(rows.map(r=>r.marginRequired)),notionalTurnover:sum(rows.map(r=>r.positionValue)),grossProfit,grossLoss,brokeragePaid:sum(rows.map(r=>r.brokerage)),taxesPaid:sum(rows.map(r=>r.taxes)),slippageCost:sum(rows.map(r=>r.slippage)),totalCharges:sum(rows.map(r=>r.totalCharges)),netProfit,endingCapital:start+netProfit,roi:start?netProfit/start*100:0,profitFactor:netLosing?netWinning/netLosing:netWinning,maximumDrawdown,averageProfitPerTrade:wins.length?netWinning/wins.length:0,averageLossPerTrade:losses.length?netLosing/losses.length:0,bestDay,worstDay,maximumDailyProfit:Math.max(0,...daily.map(d=>d.netProfit)),maximumDailyLoss:Math.abs(Math.min(0,...daily.map(d=>d.netProfit))),daily,trades:rows};
}
