'use client';
import { useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { CapitalMode, HistoricalBacktestTrade, simulateHistoricalTrades } from '../lib/backtest-capital-simulation';
import { paperTradingService } from '../lib/trading-services';
type Mode='today'|'last7'|'historical';
type BacktestData=Record<'entryTriggered'|'target1Confirmation',{trades:HistoricalBacktestTrade[]}>;
type SessionResponse={mode:Mode;sessionDate:string|null;sessionDates:string[];sourceTradeCount:number;counts:Record<'signalsFound'|'waiting'|'entryTriggered'|'running'|'target1Hit'|'target2Hit'|'target3Hit'|'completed'|'winningTrades'|'losingTrades'|'stopLoss',number>;backtest:BacktestData};
const presets=[1_000,2_000,5_000,10_000,25_000,50_000,100_000],money=(value:number)=>`₹${Number(value).toLocaleString('en-IN',{maximumFractionDigits:2})}`,inputClass='mt-2 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400/50';
const prettyDate=(value:string)=>new Date(`${value}T00:00:00+05:30`).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric'});
export function BacktestCapitalDashboard({session}:{session:string}){
 const[mode,setMode]=useState<Mode>('today'),[limit,setLimit]=useState(500),[strategy,setStrategy]=useState<keyof BacktestData>('entryTriggered'),[capital,setCapital]=useState(10_000),[brokerage,setBrokerage]=useState(20),[slippage,setSlippage]=useState(.05),[risk,setRisk]=useState(1),[capitalMode,setCapitalMode]=useState<CapitalMode>('fixed');
 const query=useQuery({queryKey:['capital-simulation',mode,limit],queryFn:()=>paperTradingService.capitalSimulation<SessionResponse>(mode,limit),enabled:Boolean(session),retry:false,refetchInterval:mode==='today'?1_000:false,staleTime:0,gcTime:0});
 const data=query.data,trades=data?.backtest?.[strategy]?.trades??[],result=useMemo(()=>simulateHistoricalTrades(trades,capital,brokerage,slippage,risk,capitalMode),[trades,capital,brokerage,slippage,risk,capitalMode]);
 const sessionLabel=data?.sessionDate?prettyDate(data.sessionDate):data?.sessionDates.length?`${prettyDate(data.sessionDates.at(-1)!)} – ${prettyDate(data.sessionDates[0])}`:'No session data';
 const card=(title:string,value:string|number,tone='text-white')=><div className="rounded-lg border border-slate-800 bg-slate-950/40 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">{title}</p><p className={`mt-2 text-sm font-black ${tone}`}>{value}</p></div>;
 const metrics:Array<[string,string|number,string?]>=[['Selected Capital',money(result.startingCapital)],['Capital Per Trade',money(result.capitalPerTrade)],['Trades Completed',result.totalTrades],['Winning Trades',result.winningTrades,'text-emerald-300'],['Losing Trades',result.losingTrades,'text-rose-300'],['Peak Margin Used',money(result.peakMarginUsed)],['Capital Turnover',money(result.capitalTurnover)],['Notional Turnover',money(result.notionalTurnover)],['Gross Profit',money(result.grossProfit),'text-emerald-300'],['Gross Loss',money(result.grossLoss),'text-rose-300'],['Brokerage',money(result.brokeragePaid)],['Taxes',money(result.taxesPaid)],['Slippage',money(result.slippageCost)],['Total Charges',money(result.totalCharges),'text-amber-300'],['NET PROFIT',money(result.netProfit),result.netProfit>=0?'text-emerald-300':'text-rose-300'],['NET ROI',`${result.roi.toFixed(2)}%`,result.roi>=0?'text-emerald-300':'text-rose-300']];
 const valid=Boolean(data&&data.sourceTradeCount===data.counts.completed),complete=result.totalTrades===result.winningTrades+result.losingTrades;
 return <section className="glass-card overflow-hidden"><header className="border-b border-slate-800 p-5"><p className="section-eyebrow">INVESTMENT SIMULATOR · INTRADAY MARGIN MODE</p><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-white">Intraday Capital Simulation</h2><p className="mt-1 text-xs text-cyan-300">Session: {sessionLabel}</p></div><div className="flex gap-2">{([['today','Today'],['last7','Last 7 Days'],['historical','Historical']] as const).map(([value,label])=><button key={value} onClick={()=>setMode(value)} className={`rounded-lg border px-3 py-2 text-xs font-black ${mode===value?'border-cyan-400/40 bg-cyan-400/10 text-cyan-300':'border-slate-700 text-slate-400'}`}>{label}</button>)}</div></div></header>
 {query.isLoading&&<div className="p-10 text-center text-sm text-slate-500">Loading session data…</div>}{query.isError&&<div className="m-5 rounded-lg bg-rose-400/10 p-4 text-sm text-rose-300">Session data could not be loaded.</div>}
 {data&&!valid&&<div className="m-5 rounded-lg bg-amber-400/10 p-4 text-sm text-amber-200">Signal History synchronization is incomplete; financial results are hidden.</div>}
 {valid&&<><div className="grid gap-3 border-b border-slate-800 p-5 sm:grid-cols-2 lg:grid-cols-6"><Field label="Strategy"><select value={strategy} onChange={e=>setStrategy(e.target.value as keyof BacktestData)} className={inputClass}><option value="entryTriggered">Entry Triggered</option><option value="target1Confirmation">Target 1 Confirmation</option></select></Field><Field label="Capital Per Trade"><input type="number" min={1_000} value={capital} onChange={e=>setCapital(Math.max(1_000,Number(e.target.value)))} className={inputClass}/></Field><Field label="Capital Mode"><select value={capitalMode} onChange={e=>setCapitalMode(e.target.value as CapitalMode)} className={inputClass}><option value="fixed">Fixed Capital Per Trade</option><option value="compounding">Compounding</option><option value="sequential">Sequential Account Balance</option></select></Field><Field label="Risk Per Trade %"><input type="number" min={.1} max={100} step={.1} value={risk} onChange={e=>setRisk(Math.max(.1,Math.min(100,Number(e.target.value))))} className={inputClass}/></Field><Field label="Brokerage / Round Trip"><input type="number" min={0} value={brokerage} onChange={e=>setBrokerage(Math.max(0,Number(e.target.value)))} className={inputClass}/></Field><Field label="Slippage %"><input type="number" min={0} step={.01} value={slippage} onChange={e=>setSlippage(Math.max(0,Number(e.target.value)))} className={inputClass}/></Field></div>
 <div className="border-b border-slate-800 p-5"><div className="flex flex-wrap gap-2">{presets.map(value=>{const preset=simulateHistoricalTrades(trades,value,brokerage,slippage,risk,capitalMode);return<button key={value} onClick={()=>setCapital(value)} className={`min-w-32 rounded-lg border p-3 text-left ${capital===value?'border-cyan-400/40 bg-cyan-400/10':'border-slate-800'}`}><b className="block text-xs text-white">{money(value)}</b><span className={preset.netProfit>=0?'text-[10px] text-emerald-300':'text-[10px] text-rose-300'}>{money(preset.netProfit)} · {preset.roi.toFixed(2)}%</span></button>})}</div></div>
 {!complete&&<div className="m-5 rounded-lg bg-rose-400/10 p-3 text-sm text-rose-300">Replay integrity failed: completed trades do not equal wins plus losses.</div>}{result.excludedTrades>0&&<div className="m-5 rounded-lg bg-amber-400/10 p-3 text-sm text-amber-200">{result.excludedTrades} trades were excluded because broker intraday margin, price, stop, or affordable quantity was unavailable.</div>}
 <div className="grid gap-2 p-5 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">{metrics.map(([title,value,tone])=><div key={title}>{card(title,value,tone)}</div>)}</div>
 <div className="overflow-auto border-t border-slate-800"><h3 className="p-4 text-sm font-black text-white">INTRADAY TRADE REPLAY</h3><table className="w-full min-w-[1900px] text-left text-xs"><thead className="bg-slate-950/60 text-slate-500"><tr>{['Date / Time','Stock','Side','Entry','Exit','Qty','Leverage','Position Value','Margin Required','Gross P&L','Brokerage','STT','Exchange','GST','SEBI','Stamp Duty','Slippage','Net P&L','Capital Before','Capital After','Exit Reason'].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{result.trades.map(row=><tr key={`${row.signalId}-${row.entryTime}`} className="border-t border-slate-800 text-slate-300"><td className="px-3 py-3">{new Date(row.entryTime).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td className="font-black text-white">{row.symbol}</td><td>{row.side}</td><td>{money(row.entryPrice)}</td><td>{money(row.exitPrice)}</td><td>{row.quantity}</td><td>{row.leverage.toFixed(2)}×</td><td>{money(row.positionValue)}</td><td>{money(row.marginRequired)}</td><td className={row.grossPnl>=0?'text-emerald-300':'text-rose-300'}>{money(row.grossPnl)}</td><td>{money(row.brokerage)}</td><td>{money(row.stt)}</td><td>{money(row.exchangeCharges)}</td><td>{money(row.gst)}</td><td>{money(row.sebiCharges)}</td><td>{money(row.stampDuty)}</td><td>{money(row.slippage)}</td><td className={row.netPnl>=0?'font-black text-emerald-300':'font-black text-rose-300'}>{money(row.netPnl)}</td><td>{money(row.capitalBefore)}</td><td>{money(row.capitalAfter)}</td><td>{row.exitReason}</td></tr>)}</tbody></table></div>
 {mode==='historical'&&<div className="p-4 text-center"><button onClick={()=>setLimit(v=>Math.min(5_000,v+500))} className="rounded-lg border border-slate-700 px-4 py-2 text-xs font-black text-slate-300">Load More Historical Trades</button></div>}</>}</section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return<label><span className="metric-label">{label}</span>{children}</label>}
