'use client';
import { useQuery } from '@tanstack/react-query';
import { Download } from 'lucide-react';
import { useMemo, useState } from 'react';
import { api } from '../lib/api';
import { ClosedTradeReport, downloadClosedTradeReport } from '../lib/closed-trade-report';

const date = (value: Date) => new Date(value.getTime() + 330 * 60_000).toISOString().slice(0,10);
const range = (preset: string) => { const now=new Date(), today=date(now), base=new Date(`${today}T00:00:00+05:30`), add=(days:number)=>{const d=new Date(base);d.setUTCDate(d.getUTCDate()+days);return date(d);}, weekday=(new Date(today + 'T12:00:00Z').getUTCDay()+6)%7;
  if(preset==='Today')return [today,today];if(preset==='Yesterday')return [add(-1),add(-1)];if(preset==='This Week')return [add(-weekday),today];if(preset==='Last Week')return [add(-weekday-7),add(-weekday-1)];if(preset==='Last 7 Days')return [add(-6),today];if(preset==='Last 14 Days')return [add(-13),today];if(preset==='This Month')return [`${today.slice(0,8)}01`,today];const first=new Date(`${today.slice(0,8)}01T00:00:00+05:30`);first.setUTCDate(first.getUTCDate()-1);const end=date(first);return [`${end.slice(0,8)}01`,end]; };
const money=(value:number)=>value.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
export function ClosedTradeHistory({session}:{session:string}){
  const [preset,setPreset]=useState('Today'), [side,setSide]=useState('ALL'), [reason,setReason]=useState('ALL'), [view,setView]=useState({page:1,sortBy:'exitTime',sort:'desc'}), initial=range('Today'), [start,setStart]=useState(initial[0]), [end,setEnd]=useState(initial[1]), [downloading,setDownloading]=useState(false), [downloadError,setDownloadError]=useState(''), {page,sortBy,sort}=view;
  const query=useQuery({queryKey:['closed-trade-history',session,start,end,side,reason,page,sortBy,sort],queryFn:async()=>{const url=`/paper-trading/history?${new URLSearchParams({start,end,page:String(page),pageSize:'25',sortBy,sort,...(side==='ALL'?{}:{side}),...(reason==='ALL'?{}:{reason})})}`;console.info('[closed-trade-history] request',{url,start,end,side,reason,page,sortBy,sort});try{const report=await api<ClosedTradeReport>(url);console.info('[closed-trade-history] response',{trades:report.summary.totalTrades,rows:report.rows.length,range:report.range});return report}catch(error){console.error('[closed-trade-history] request failed',{url,error});throw error}},enabled:Boolean(session),refetchInterval:30000});
  const data=query.data, max=Math.max(1,...(data?.daily.map(day=>Math.abs(day.netPnl))??[1]));
  const selectPreset=(value:string)=>{const [from,to]=range(value);setPreset(value);setStart(from);setEnd(to);setView(value=>({...value,page:1}));};
  const cards=useMemo(()=>data?[['Balance before trades',money(data.summary.openingBalance)],['Balance after trades',money(data.summary.closingBalance)],['Total trades',data.summary.totalTrades],['Winning trades',data.summary.winningTrades],['Losing trades',data.summary.losingTrades],['Breakeven',data.summary.breakevenTrades],['Gross profit',money(data.summary.grossProfit)],['Gross loss',money(data.summary.grossLoss)],['Brokerage',money(data.summary.brokerage)],['Other charges',money(data.summary.otherCharges)],['Total charges',money(data.summary.totalCharges)],['Final net P&L',money(data.summary.netPnl)],['Win rate',`${data.summary.winRate.toFixed(1)}%`],['Avg winner',money(data.summary.averageProfit)],['Avg loser',money(data.summary.averageLoss)],['Margin used',money(data.summary.totalMarginUsed)]]:[],[data]);
  return <section className="glass-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-white">Closed Trades · Trade History</h3><p className="mt-1 text-xs text-slate-500">Database-backed realized paper trades · Exit dates use Asia/Kolkata</p></div><button disabled={!data||downloading} className="primary-button" onClick={async()=>{if(!data)return;setDownloading(true);setDownloadError('');try{let report:ClosedTradeReport={...data,allRows:data.rows};if(data.pagination.total>data.rows.length){const params=new URLSearchParams({start,end,export:'true',sortBy,sort,...(side==='ALL'?{}:{side}),...(reason==='ALL'?{}:{reason})});const url='/paper-trading/history?'+params;console.info('[closed-trade-history] PDF request',{url});report=await api<ClosedTradeReport>(url)}await downloadClosedTradeReport(report);console.info('[closed-trade-history] PDF downloaded',{rows:report.allRows.length,range:report.range})}catch(error){const message=error instanceof Error?error.message:'PDF download failed';console.warn('[closed-trade-history] PDF download failed',{message});setDownloadError(message)}finally{setDownloading(false)}}}><Download className="h-4 w-4"/>{downloading?'Preparing PDF…':'Download PDF'}</button></div>
  {downloadError&&<p className="mt-3 text-sm text-rose-300">PDF download failed: {downloadError}</p>}
  <div className="mt-4 flex flex-wrap gap-2">{['Today','Yesterday','This Week','Last Week','Last 7 Days','Last 14 Days','This Month','Last Month'].map(item=><button key={item} onClick={()=>selectPreset(item)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${preset===item?'border-cyan-400/35 bg-cyan-400/10 text-cyan-300':'border-slate-700 text-slate-400'}`}>{item}</button>)}</div>
  <div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-xs text-slate-400">Start<input type="date" value={start} onChange={e=>{setPreset('Custom');setStart(e.target.value);setView(value=>({...value,page:1}))}} className="ml-2 rounded border border-slate-700 bg-slate-950 p-2"/></label><label className="text-xs text-slate-400">End<input type="date" value={end} min={start} onChange={e=>{setPreset('Custom');setEnd(e.target.value);setView(value=>({...value,page:1}))}} className="ml-2 rounded border border-slate-700 bg-slate-950 p-2"/></label>{['ALL','BUY','SELL'].map(item=><button key={item} onClick={()=>{setSide(item);setView(value=>({...value,page:1}))}} className={`rounded border px-3 py-2 text-xs ${side===item?'border-cyan-400 text-cyan-300':'border-slate-700'}`}>{item==='ALL'?'All sides':item}</button>)}{['ALL','COMPLETED','STOPLOSS','MANUAL'].map(item=><button key={item} onClick={()=>{setReason(item);setView(value=>({...value,page:1}))}} className={`rounded border px-3 py-2 text-xs ${reason===item?'border-cyan-400 text-cyan-300':'border-slate-700'}`}>{item==='ALL'?'All exits':item==='STOPLOSS'?'Stop Loss':item==='MANUAL'?'Manual Exit':'Completed'}</button>)}<label className="text-xs text-slate-400">Sort<select value={sortBy} onChange={e=>{setView(value=>({...value,sortBy:e.target.value,page:1}))}} className="ml-2 rounded border border-slate-700 bg-slate-950 p-2"><option value="exitTime">Exit time</option><option value="entryTime">Entry time</option><option value="symbol">Stock</option><option value="grossPnl">Gross P&amp;L</option><option value="netPnl">Net P&amp;L</option><option value="durationMinutes">Duration</option></select></label><select aria-label="Sort direction" value={sort} onChange={e=>{setView(value=>({...value,sort:e.target.value,page:1}))}} className="rounded border border-slate-700 bg-slate-950 p-2 text-xs"><option value="desc">Descending</option><option value="asc">Ascending</option></select></div>
  {query.isError&&<p className="mt-4 text-sm text-rose-300">{query.error.message}</p>}{query.isLoading&&<p className="mt-4 text-sm text-slate-400">Loading closed trades…</p>}
  {data&&<><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{cards.map(([label,value])=><div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className={`mt-2 font-black ${label==='Final net P&L'?(data.summary.netPnl>=0?'text-emerald-300':'text-rose-300'):'text-white'}`}>{value}</p></div>)}</div>
  <div className="mt-5 rounded-xl border border-slate-800 p-4"><p className="text-xs font-bold uppercase text-slate-400">Daily net profit / loss</p><div className="mt-4 flex h-36 items-center gap-2 overflow-x-auto">{data.daily.map(day=><div key={day.date} className="flex min-w-14 flex-1 flex-col items-center justify-center"><div className={`w-6 rounded ${day.netPnl>=0?'bg-emerald-400':'bg-rose-400'}`} style={{height:`${Math.max(2,Math.abs(day.netPnl)/max*92)}px`}}/><p className="mt-2 text-[9px] text-slate-500">{day.date.slice(5)}</p><p className={`text-[9px] ${day.netPnl>=0?'text-emerald-300':'text-rose-300'}`}>{money(day.netPnl)}</p></div>)}</div></div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1900px] text-left text-xs"><thead><tr className="border-b border-slate-700 text-slate-500">{['Entry Time','Exit Time','Stock','BUY / SELL','Entry Price','Exit Price','Quantity','Margin Used','Gross P&L','Brokerage','Other Charges','Total Charges','Net P&L','Net P&L %','Exit Reason','Duration'].map(h=><th className="px-3 py-3 uppercase" key={h}>{h}</th>)}</tr></thead><tbody>{data.rows.map(row=><tr key={row.id} className="border-b border-slate-800"><td className="px-3 py-3">{new Date(row.entryTime).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td className="px-3 py-3">{new Date(row.exitTime).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td className="px-3 py-3 font-bold text-white">{row.symbol}</td><td className="px-3 py-3">{row.side}</td><td className="px-3 py-3">{money(row.entryPrice)}</td><td className="px-3 py-3">{money(row.exitPrice)}</td><td className="px-3 py-3">{row.quantity}</td><td className="px-3 py-3">{money(row.marginUsed)}</td><td className={`px-3 py-3 ${row.grossPnl>=0?'text-emerald-300':'text-rose-300'}`}>{money(row.grossPnl)}</td><td className="px-3 py-3">{money(row.brokerage)}<p className="text-[9px] text-slate-500">Entry {money(row.entryBrokerage)} · Exit {money(row.exitBrokerage)}</p></td><td className="px-3 py-3">{money(row.otherCharges)}</td><td className="px-3 py-3">{money(row.totalCharges)}<p className="text-[9px] text-amber-200">{row.chargesSource.startsWith('ESTIMATED')?'Estimated':'Broker reported'}</p></td><td className={`px-3 py-3 font-bold ${row.netPnl>=0?'text-emerald-300':'text-rose-300'}`}>{money(row.netPnl)}</td><td className="px-3 py-3">{row.netPnlPercent.toFixed(2)}%</td><td className="px-3 py-3">{row.exitReason}</td><td className="px-3 py-3">{row.durationMinutes} min</td></tr>)}</tbody></table>{!data.rows.length&&<p className="py-10 text-center text-slate-500">No genuinely closed trades match these filters.</p>}</div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead><tr className="text-slate-500">{['Date','Opening Balance','Closing Balance','Total Trades','Wins','Losses','Gross Profit','Gross Loss','Brokerage','Other Charges','Net P&L','Win Rate'].map(h=><th className="px-3 py-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.daily.map(day=><tr key={day.date} className="border-t border-slate-800"><td className="px-3 py-3">{day.date}</td><td className="px-3 font-bold text-white">{money(day.openingBalance)}</td><td className="px-3 font-bold text-cyan-300">{money(day.closingBalance)}</td><td className="px-3">{day.totalTrades}</td><td className="px-3">{day.wins}</td><td className="px-3">{day.losses}</td><td className="px-3 text-emerald-300">{money(day.grossProfit)}</td><td className="px-3 text-rose-300">{money(day.grossLoss)}</td><td className="px-3">{money(day.brokerage)}</td><td className="px-3">{money(day.otherCharges)}</td><td className={`px-3 font-bold ${day.netPnl>=0?'text-emerald-300':'text-rose-300'}`}>{money(day.netPnl)}</td><td className="px-3">{day.winRate.toFixed(1)}%</td></tr>)}</tbody></table></div>
  {data.pagination.pages>1&&<div className="mt-4 flex justify-end gap-2"><button disabled={page<=1} onClick={()=>setView(value=>({...value,page:page-1}))} className="rounded border border-slate-700 px-3 py-2">Previous</button><span className="px-3 py-2 text-xs">Page {page} / {data.pagination.pages}</span><button disabled={page>=data.pagination.pages} onClick={()=>setView(value=>({...value,page:page+1}))} className="rounded border border-slate-700 px-3 py-2">Next</button></div>}</>}</section>;
}
