'use client';

import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowDownRight, ArrowUpRight, Radio, ScanLine, TrendingDown, TrendingUp } from 'lucide-react';
import { io } from 'socket.io-client';
import { useEffect, useMemo, useState } from 'react';
import { base, token, upstoxLoginUrl } from '../lib/api';

const indices = [{ name: 'NIFTY 50', instrumentKey: 'NSE_INDEX|Nifty 50' }, { name: 'BANK NIFTY', instrumentKey: 'NSE_INDEX|Nifty Bank' }, { name: 'FINNIFTY', instrumentKey: 'NSE_INDEX|Nifty Fin Service' }, { name: 'MIDCAP 100', instrumentKey: 'NSE_INDEX|NIFTY MIDCAP 100' }, { name: 'SENSEX', instrumentKey: 'BSE_INDEX|SENSEX' }];
function dataForInstrument(data: Record<string, any>, instrumentKey: string) { const key = Object.keys(data).find((candidate) => candidate === instrumentKey || candidate.replace(':', '|') === instrumentKey || data[candidate]?.instrument_token === instrumentKey); return key ? data[key] : undefined; }
const toPrice = (value: number) => Number.isFinite(value) ? value.toLocaleString('en-IN', { maximumFractionDigits: 2 }) : '—';
function Summary({ label, value, Icon, tone }: { label: string; value: string | number; Icon: typeof Activity; tone: string }) { return <div className="glass-card p-4"><div className="flex items-center justify-between"><span className="metric-label">{label}</span><Icon className={`h-4 w-4 ${tone}`} /></div><p className="mt-3 text-2xl font-bold tracking-tight text-white">{value}</p></div>; }

export function LiveDashboard({ session }: { session: string }) {
  const [ticks, setTicks] = useState<Record<string, any>>({});
  const market = useQuery({ queryKey: ['upstox-live-indices'], queryFn: async () => { const response = await fetch(`${base}/market/indices`, { headers: { Authorization: `Bearer ${token()}` } }); if (!response.ok) throw new Error(await response.text()); return response.json(); }, enabled: Boolean(session), retry: false, refetchInterval: 30_000 });
  const summary = useQuery({ queryKey: ['live-dashboard-summary'], queryFn: async () => { const response = await fetch(`${base}/dashboard`, { headers: { Authorization: `Bearer ${token()}` } }); if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<{ scannerCount: number; topBuy: unknown[]; topSell: unknown[] }>; }, enabled: Boolean(session), retry: false, refetchInterval: 60_000 });
  useEffect(() => { const sessionToken = token(); if (!sessionToken) return; const socket = io(base, { auth: { token: sessionToken }, reconnection: true, reconnectionDelay: 1_000, reconnectionDelayMax: 5_000 }); socket.on('market-tick', (tick) => setTicks((current) => ({ ...current, ...(tick.feeds ?? {}) }))); return () => { socket.close(); }; }, []);
  const quote = market.data?.quote?.data ?? market.data?.quote ?? {}; const liveIndices = useMemo(() => indices.map((index) => { const rest = dataForInstrument(quote, index.instrumentKey); const feed = ticks[index.instrumentKey]; const ltpc = feed?.ltpc ?? feed?.fullFeed?.indexFF?.ltpc ?? feed?.fullFeed?.marketFF?.ltpc; const price = Number(ltpc?.ltp ?? rest?.last_price); const close = Number(ltpc?.cp ?? rest?.ohlc?.close ?? rest?.cp); const percent = Number.isFinite(price) && Number.isFinite(close) && close ? (price - close) / close * 100 : null; return { ...index, price, percent }; }), [quote, ticks]);
  return <div><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="section-eyebrow">QUANTPULSE LIVE TERMINAL</p><h1 className="text-3xl font-bold tracking-tight text-white">Market overview</h1><p className="mt-2 text-sm text-slate-400">Live Upstox market feed, ranked setups, and scan coverage.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/[.07] px-3 py-2 text-xs font-bold text-emerald-300"><span className="live-dot" /><Radio className="h-3.5 w-3.5" />NSE LIVE</div></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary label="Market status" value="NSE Live" Icon={Radio} tone="text-emerald-400" /><Summary label="Stocks scanned" value={summary.data?.scannerCount ?? '—'} Icon={ScanLine} tone="text-sky-400" /><Summary label="Top buy" value={summary.data?.topBuy?.length ?? '—'} Icon={TrendingUp} tone="text-emerald-400" /><Summary label="Top sell" value={summary.data?.topSell?.length ?? '—'} Icon={TrendingDown} tone="text-rose-400" /><Summary label="Last update" value={market.data ? 'Live' : '—'} Icon={Activity} tone="text-amber-400" /></section><section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{liveIndices.map((index) => <article className="glass-card p-4" key={index.instrumentKey}><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-300">{index.name}</span><span className={`flex items-center gap-1 text-xs font-bold ${index.percent === null ? 'text-slate-500' : index.percent >= 0 ? 'text-emerald-300' : 'text-rose-300'}`}>{index.percent === null ? 'WAITING' : <>{index.percent >= 0 ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}{index.percent.toFixed(2)}%</>}</span></div><p className="mt-4 text-xl font-bold tracking-tight text-white">{toPrice(index.price)}</p><p className="mt-1 text-[10px] text-slate-500">Authenticated Upstox feed</p></article>)}</section>{!session && <div className="mt-6 flex flex-wrap items-center justify-between gap-4 glass-card border-amber-400/20 p-5 text-sm text-amber-200"><span>Sign in with Upstox to load live market values.</span><button onClick={() => window.location.assign(upstoxLoginUrl())} className="primary-button">Connect Upstox</button></div>}{(market.isError || summary.isError) && <div className="mt-6 glass-card border-rose-400/20 p-5 text-sm text-rose-200">{market.error?.message ?? summary.error?.message}</div>}</div>;
}
