'use client';
import { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient, useMutation } from '@tanstack/react-query';
import { Activity, AlertTriangle, CheckCircle2, Settings2, ShieldCheck } from 'lucide-react';
import { io } from 'socket.io-client';
import { api, base } from '../lib/api';
import { mergeNiftyMarket, markNiftySignals } from '../lib/nifty';
import type { CandleResponse, NiftyView, Performance, Settings, Signal } from '../lib/nifty';
import { NiftyDemoAccount } from './nifty-demo-account';
import { NiftyChart } from './nifty-chart';
import type { ChartLevel } from './chart';
const names: Record<string, string> = { TREND_PULLBACK: 'Trend Pullback', BREAKOUT_RETEST: 'Breakout + Retest', VWAP_RECLAIM_REJECTION: 'VWAP Reclaim / Rejection', RANGE_REVERSAL: 'Support Bounce / Resistance Rejection' };
const num = (v: number | null | undefined, digits = 2) => v == null ? '—' : v.toLocaleString('en-IN', { maximumFractionDigits: digits, minimumFractionDigits: digits });
const time = (v: string | number | null | undefined) => v == null ? '—' : new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', second: '2-digit', day: '2-digit', month: 'short' }).format(new Date(v));
function Metric({ label, value }: {
  label: string;
  value: string;
}) { return <div><p className="metric-label">{label}</p><p className="metric-value">{value}</p></div>; }
function Panel({ title, children }: {
  title: string;
  children: React.ReactNode;
}) { return <section className="glass-card p-5"><h2 className="mb-4 text-sm font-semibold text-slate-100">{title}</h2>{children}</section>; }
function NiftyAnalysis({ session }: {
  session: string;
}) {
  const client = useQueryClient();
  const [tf, setTf] = useState(15), [now, setNow] = useState(Date.now()), [connected, setConnected] = useState(false), [editing, setEditing] = useState(false), [indicators, setIndicators] = useState(['ema20', 'ema50', 'vwap', 'volume']), [showLevels, setShowLevels] = useState(true), [from, setFrom] = useState(''), [to, setTo] = useState(''), [filter, setFilter] = useState(''), [side, setSide] = useState(''), [regime, setRegime] = useState(''), [windowFilter, setWindowFilter] = useState('');
  const view = useQuery({ queryKey: ['nifty', 'market', session], queryFn: async () => mergeNiftyMarket(await api<NiftyView>('/nifty/market'), client.getQueryData<NiftyView>(['nifty', 'market', session])), enabled: !!session, refetchInterval: 5000, retry: false });
  const candles = useQuery({ queryKey: ['nifty', 'candles', tf, session], queryFn: () => api<CandleResponse>(`/nifty/candles?timeframe=${tf}`), enabled: !!session, refetchInterval: 5000, retry: false });
  const history = useQuery({ queryKey: ['nifty', 'signals', session, from, to, filter, side, regime, windowFilter], queryFn: async () => markNiftySignals(await api<Signal[]>(`/nifty/signals?${new URLSearchParams({ ...from ? { from } : {}, ...to ? { to } : {}, ...filter ? { strategy: filter } : {}, ...side ? { side } : {}, ...regime ? { regime } : {}, ...windowFilter ? { window: windowFilter } : {} })}`), client.getQueryData<NiftyView>(['nifty','market',session])?.market??null), enabled: !!session, refetchInterval: 10000, retry: false });
  const filteredPerformance = useQuery({ queryKey: ['nifty', 'performance', session, from, to, filter, side, regime, windowFilter], queryFn: () => api<Performance>(`/nifty/performance?${new URLSearchParams({ ...from ? { from } : {}, ...to ? { to } : {}, ...filter ? { strategy: filter } : {}, ...side ? { side } : {}, ...regime ? { regime } : {}, ...windowFilter ? { window: windowFilter } : {} })}`), enabled: !!session && !!(from || to || filter || side || regime || windowFilter), refetchInterval: 30000 });
  const backtest = useMutation({ mutationFn: () => api<Performance>(`/nifty/backtest?${new URLSearchParams({from,to,...filter?{strategy:filter}:{},...regime?{regime}:{},...windowFilter?{window:windowFilter}:{}})}`) });
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (!session)
    return; const socket = io(base, { auth: { token: session }, transports: ['websocket', 'polling'] }); let dirty = false; const update = () => { dirty = true; }; socket.on('connect', () => setConnected(true)); socket.on('disconnect', () => setConnected(false)); socket.on('nifty.price', (tick: {
    timestampTrusted: boolean;
    ltp: number;
    timestamp: number;
  }) => { client.setQueryData<NiftyView>(['nifty', 'market', session], old => old?.market && tick.timestamp >= old.market.timestamp ? { ...old, market: { ...old.market, ...tick } } : old); client.setQueriesData<Signal[]>({queryKey:['nifty','signals',session]}, rows=>rows?markNiftySignals(rows,client.getQueryData<NiftyView>(['nifty','market',session])?.market??null):rows); }); for (const event of ['nifty.candle', 'nifty.regime', 'nifty.signal', 'nifty.signal.update', 'nifty.trade-progress'])
    socket.on(event, update); const timer = setInterval(() => { if (dirty) {
    dirty = false;
    void client.invalidateQueries({ queryKey: ['nifty'] });
  } }, 2000); return () => { clearInterval(timer); socket.disconnect(); }; }, [session, client]);
  const v = view.data;
  const age = v?.market ? Math.max(0, now - v.market.timestamp) : null;
  const stale = !!v?.dataHealth?.stale || !v?.market?.timestampTrusted || age === null || age > (v?.settings.staleMs ?? 15000);
  const active = history.data?.find(s => !['TARGET_3_HIT', 'STOP_LOSS', 'AUTO_EXIT', 'BREAKEVEN', 'CANCELLED', 'EXPIRED'].includes(s.status));
  const setup = v?.setup;
  const trade = active ? { entry: active.entryPrice, stopLoss: active.stopLoss, target1: active.target1, target2: active.target2, target3: active.target3, risk: Math.abs(active.entryPrice - active.stopLoss), riskReward: 2 } : setup?.trade;
  const levels = useMemo(() => { const out: ChartLevel[] = []; if (showLevels)
    for (const [key, label] of [['previousDayHigh', 'PDH'], ['previousDayLow', 'PDL'], ['previousClose', 'Previous close'], ['openingRangeHigh', 'OR high'], ['openingRangeLow', 'OR low'], ['support', 'Support'], ['resistance', 'Resistance']]) {
      const p = v?.levels[key];
      if (typeof p === 'number')
        out.push({ price: p, label, color: '#64748b' });
    } if (trade)
    for (const [key, label, color] of [['entry', 'ENTRY', '#60a5fa'], ['stopLoss', 'SL', '#fb7185'], ['target1', 'T1', '#34d399'], ['target2', 'T2', '#34d399'], ['target3', 'T3', '#34d399']] as const)
      out.push({ price: trade[key], label, color }); return out; }, [v?.levels, trade?.entry, trade?.stopLoss, trade?.target1, trade?.target2, trade?.target3, showLevels]);
  if (!session)
    return <Panel title="NIFTY 50"><p className="text-sm text-slate-400">Connect Upstox to receive authenticated Nifty prices, candles and option contracts.</p></Panel>;
  const reasons = active ? JSON.parse(active.niftyContext.reasons) as string[] : setup?.reasons ?? [];
  const invalidations = active ? JSON.parse(active.niftyContext.invalidations) as string[] : setup?.invalidations ?? [];
  const option = active ? JSON.parse(active.niftyContext.optionContract) as NiftyView['option'] : v?.option;
  return <div className="space-y-5">
<section className="flex flex-wrap items-start justify-between gap-5 border-b border-white/10 pb-5"><div><p className="section-eyebrow">INTRADAY ANALYSIS · NSE · UNDERLYING FIRST</p><h1 className="text-xl font-semibold">NIFTY 50</h1><p className="mt-2 text-4xl font-semibold tracking-tight tabular-nums">{num(v?.market?.ltp)}</p><p className={`mt-2 text-sm ${(v?.market?.ltp ?? 0) >= (v?.market?.close ?? Infinity) ? 'text-emerald-300' : 'text-rose-300'}`}>{v?.market?.close ? `${num(v.market.ltp - v.market.close)} (${num((v.market.ltp / v.market.close - 1) * 100)}%)` : 'Previous close unavailable'}</p></div><div className="text-right"><span className={`text-xs font-semibold ${stale ? 'text-amber-300' : 'text-emerald-300'}`}>{v?.session.status !== 'OPEN' ? 'MARKET CLOSED' : stale ? 'DATA DELAYED' : '● LIVE'}</span>{(stale || v?.session.status !== 'OPEN') && <p className="mt-1 text-xs text-amber-300">NEW TRADES DISABLED</p>}<p className="mt-2 text-xs text-slate-400">Updated {time(v?.market?.timestamp)} IST</p><p className="mt-1 text-xs text-slate-500">{age === null ? 'No market tick' : `Data age: ${(age / 1000).toFixed(1)} sec`}</p><p className="mt-3 text-xs text-sky-300">{v?.session.status ?? 'CHECKING SESSION'} · {time(v?.session.open)} – {time(v?.session.close)}</p><button onClick={() => setEditing(!editing)} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs"><Settings2 size={14}/>Nifty settings</button></div><div className="grid w-full grid-cols-2 gap-4 sm:grid-cols-5">{[['Open', v?.market?.open], ['High', v?.market?.high], ['Low', v?.market?.low], ['Prev close', v?.market?.close], ['Volume', v?.market?.volume || null]].map(([label, value]) => <Metric key={String(label)} label={String(label)} value={num(value as number | null)}/>)}</div></section>
{(view.error || candles.error || history.error) && <div role="alert" className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{(view.error ?? candles.error ?? history.error)?.message}<button onClick={() => void client.invalidateQueries({ queryKey: ['nifty'] })} className="ml-4 underline">Retry</button></div>}
{v && <Panel title="TODAY"><div className="grid grid-cols-3 gap-4"><Metric label="Opportunities" value={`${v.today.opportunities} / ${v.today.target}`}/><Metric label="Trades" value={`${v.today.trades} / ${v.today.maxTrades}`}/><Metric label="Remaining opportunity target" value={String(v.today.remaining)}/></div></Panel>}
{v && <Panel title="Live data health"><p className="mb-3 text-xs text-slate-400">Broker WebSocket: {v.dataHealth.websocketStatus} · Page connection: {connected ? 'CONNECTED' : 'POLLING'} · Tick age: {age === null ? 'N/A' : `${age}ms`} · Latest tick: {time(v.dataHealth.latestTick)}</p><div className="grid gap-4 sm:grid-cols-4">{v.dataHealth.timeframes.map(t=><div key={t.timeframe} className="text-xs text-slate-400"><p>{t.timeframe}M: {v.session.status !== 'OPEN' ? 'CLOSED' : t.status}</p><p>Latest: {time(t.latest)}</p><p>Closed: {time(t.latestClosed)}</p><p>Candle age: {t.ageMs === null ? 'N/A' : `${Math.max(0,now-Date.parse(t.latest!))}ms`}</p></div>)}</div><p className="mt-3 text-xs text-slate-500">Index volume may be unavailable. VWAP requires actual traded volume; price strategies use their own required inputs.</p></Panel>}
{editing && v && <NiftySettings settings={v.settings} onSaved={() => { setEditing(false); void client.invalidateQueries({ queryKey: ['nifty'] }); }}/>}
<div className="grid gap-4 lg:grid-cols-4"><Panel title="Market regime"><Activity size={20} className="mb-3 text-cyan-300"/><p className="text-xl font-semibold">{v?.regime ?? 'NO TRADE'}</p><p className="mt-2 text-xs text-slate-400">Structure, VWAP, EMA alignment, momentum and volume</p></Panel>{[['direction', '15M · DIRECTION'], ['setup', '5M · SETUP'], ['confirmation', '3M · CONFIRMATION']].map(([key, label]) => <Panel key={key} title={label}><p className="text-lg font-semibold">{key === 'confirmation' ? (setup?.checks.find(c => c.name === 'Entry confirmation')?.pass ? 'CONFIRMED' : 'WAITING') : key === 'setup' ? (setup?.checks.find(c => c.name === 'Setup quality')?.pass ? 'SETUP DETECTED' : 'WAITING') : v?.timeframes?.direction.direction ?? 'WAITING'}</p><p className="mt-2 text-xs text-slate-400">EMA20 {num(v?.timeframes?.[key as 'direction']?.ema20)}<br />EMA50 {num(v?.timeframes?.[key as 'direction']?.ema50)}<br />VWAP {num(v?.timeframes?.[key as 'direction']?.vwap)}</p></Panel>)}</div>
<section className="glass-card p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold">Nifty price action</h2><div className="flex gap-2">{[15, 5, 3, 1].map(t => <button key={t} onClick={() => setTf(t)} className={`rounded-lg px-3 py-1.5 text-xs ${tf === t ? 'bg-cyan-400/15 text-cyan-200' : 'text-slate-400'}`}>{t}M</button>)}</div></div><div className="mb-3 flex flex-wrap gap-4 text-xs text-slate-400">{['ema20', 'ema50', 'vwap', 'volume'].map(k => <label key={k} className="flex items-center gap-2"><input type="checkbox" checked={indicators.includes(k)} onChange={() => setIndicators(old => old.includes(k) ? old.filter(x => x !== k) : [...old, k])}/>{k.toUpperCase()}</label>)}<label><input type="checkbox" checked={showLevels} onChange={() => setShowLevels(!showLevels)}/> Key levels</label><span className="ml-auto">Exchange time · IST</span></div><NiftyChart key={tf} data={candles.data} levels={levels} enabled={indicators}/></section>
<div className="grid gap-5 xl:grid-cols-[1fr_1.6fr]"><div className="space-y-5"><Panel title="Key levels"><div className="grid grid-cols-2 gap-4">{Object.entries(v?.levels ?? {}).filter(([k, x]) => typeof x !== 'boolean' && k !== 'swingHigh' && k !== 'swingLow').map(([k, x]) => <Metric key={k} label={k.replace(/([A-Z])/g, ' $1')} value={num(x as number | null)}/>)}</div></Panel><Panel title="Strategy scanner"><div className="space-y-4">{v?.strategies.map(e => <div key={e.strategy}><div className="flex justify-between text-sm"><span>{names[e.strategy]}</span><span className="tabular-nums">{e.available === false ? 'UNAVAILABLE' : `${e.score}/100`}</span></div><div className="my-2 h-1 rounded bg-slate-800"><div className="h-1 rounded bg-cyan-400" style={{ width: `${e.score}%` }}/></div><p className="text-xs text-slate-500">{e.valid ? 'Technical conditions passed' : e.missing[0] ?? 'Waiting'}</p></div>)}</div></Panel><Panel title="Risk & reward"><div className="grid grid-cols-2 gap-4"><Metric label="Risk per trade" value={`${v?.settings.riskPercent ?? '—'}%`}/><Metric label="Maximum risk" value={`₹${num(v?.risk.maximumRisk)}`}/><Metric label="Daily risk reserved" value={`₹${num(v?.risk.reserved)}`}/><Metric label="Remaining daily risk" value={`₹${num(v?.risk.remaining)}`}/><Metric label="Trades / limit" value={`${v?.risk.trades ?? 0} / ${v?.settings.maxTrades ?? '—'}`}/><Metric label="Consecutive losses" value={String(v?.risk.consecutiveLosses ?? 0)}/></div><p className="mt-4 text-xs text-slate-500">Option sizing uses the configured premium stop. Capital reserves the full premium; lot size comes from exchange contract metadata.</p></Panel></div>
<div className="space-y-5"><Panel title={setup?.valid && !v?.noTradeReasons.length && !stale ? "BEST VALID SETUP" : "NO VALID SETUP"}><div className="flex items-center justify-between"><div><p className="text-xl font-semibold">{active ? `${active.side === 'BUY' ? 'CALL' : 'PUT'} SETUP` : v?.noTradeReasons.length || stale ? 'NO TRADE' : `${setup?.side === 'BUY' ? 'CALL' : 'PUT'} SETUP`}</p><p className="mt-2 text-sm text-slate-400">{names[active?.strategy ?? setup?.strategy ?? ''] ?? 'Collecting data'}</p></div><ShieldCheck className="text-sky-300"/></div><p className="mt-3 text-xs text-amber-300">{active?.status.replaceAll('_', ' ') ?? 'WAITING FOR CONFIRMATION'}</p>{trade && <div className="mt-5 grid grid-cols-3 gap-4">{[['Entry', trade.entry], ['Stop loss', trade.stopLoss], ['Risk points', trade.risk], ['Target 1', trade.target1], ['Target 2', trade.target2], ['Target 3', trade.target3]].map(([k, x]) => <Metric key={String(k)} label={String(k)} value={num(x as number)}/>)}<Metric label="Risk / reward" value={`1:${trade.riskReward}`}/></div>}{!active && trade && <p className="mt-4 text-xs text-slate-500">Candidate levels only. No confirmed signal while mandatory filters fail.</p>}</Panel>
<section className="glass-card border-cyan-400/20 p-5"><h2 className="mb-4 flex items-center gap-2 text-base font-semibold"><CheckCircle2 size={18} className="text-cyan-300"/>{active || setup?.valid && !v?.noTradeReasons.length ? "Why this trade?" : "Why no trade?"}</h2><p className="mb-3 text-xs text-slate-400">{active ? 'Facts captured with the canonical signal' : 'Calculated facts for the best candidate; entry is not yet authorized'}</p><ol className="space-y-2 text-sm text-slate-300">{(active || setup?.valid && !v?.noTradeReasons.length ? reasons : v?.noTradeReasons ?? []).map((r, i) => <li key={r}>{i + 1}. {r}</li>)}</ol>{!active && !!v?.waitFor.length && <div className="mt-4 text-xs text-slate-400"><p>WAIT FOR:</p>{v.waitFor.map(r=><p key={r}>{r}</p>)}</div>}{!reasons.length && <p className="text-sm text-slate-400">Waiting for sufficient closed candles.</p>}<h3 className="mb-2 mt-5 text-xs font-semibold text-rose-300">WHAT CAN INVALIDATE IT?</h3>{invalidations.map(r => <p key={r} className="mb-1 text-sm text-slate-400">• {r}</p>)}<h3 className="mb-2 mt-5 text-xs font-semibold text-amber-300">WHAT SHOULD I WAIT FOR?</h3>{(v?.noTradeReasons ?? ['Loading strategy state']).map(r => <p key={r} className="mb-1 text-sm text-slate-400">• {r}</p>)}</section>
<Panel title="Signal confirmation & setup score">{v?.historicalObservation?.sufficient && <p className="mb-3 text-xs text-sky-300">Historical observation · {num(v.historicalObservation.winRate)}% win rate · {v.historicalObservation.sampleSize} underlying simulated trades in matching strategy, direction and regime</p>}<p className="mb-4 text-2xl font-semibold">{active?.aiScore ?? v?.strategies.find(e => e.strategy === setup?.strategy)?.score ?? 0} <span className="text-sm text-slate-500">/ 100 · {((active?.aiScore ?? v?.strategies.find(e => e.strategy === setup?.strategy)?.score ?? 0) >= 85 ? 'STRONG SETUP' : (active?.aiScore ?? v?.strategies.find(e => e.strategy === setup?.strategy)?.score ?? 0) >= 75 ? 'GOOD' : (active?.aiScore ?? v?.strategies.find(e => e.strategy === setup?.strategy)?.score ?? 0) >= 60 ? 'MODERATE' : 'WEAK')}</span></p><p className="mb-4 text-xs text-slate-500">Deterministic score; it is not a win probability. Historical performance is shown separately when enough observations exist.</p>{(v?.strategies.find(e => e.strategy === setup?.strategy)?.checks ?? []).map(c => <div key={c.name} title={c.reason} className="mb-2 flex justify-between border-b border-white/5 pb-2 text-xs"><span>{c.pass ? '✓ PASS' : '○ WAIT'} · {c.name}</span><span>{c.pass ? c.weight : 0}/{c.weight}</span></div>)}</Panel>
<Panel title="Option execution instrument">{option ? <><p className="text-lg font-semibold">{option.symbol}</p><p className="mb-4 mt-1 text-xs text-slate-400">Underlying: NIFTY {active ? (active.side === 'SELL' ? 'BEARISH' : 'BULLISH') : (v?.regime ?? 'NO TRADE')} · Expiry {option.expiry}</p><div className="grid grid-cols-3 gap-4">{[['LTP', option.ltp], ['Bid', option.bid], ['Ask', option.ask], ['Spread %', option.spreadPercent], ['Volume', option.volume], ['OI', option.oi], ['IV', option.iv], ['Delta', option.delta], ['Lot size', option.lotSize], ['Quantity', option.quantity], ['Stop risk ₹', option.maximumRisk]].map(([k, x]) => <Metric key={String(k)} label={String(k)} value={num(x as number | null)}/>)}</div><p className="mt-3 text-xs text-slate-500">{active ? 'Contract snapshot at signal generation' : 'Latest eligible contract'} · {time(option.timestamp)} IST</p></> : <p className="text-sm text-slate-400">No eligible contract passed freshness, spread, volume and affordable-lot checks.</p>}</Panel></div></div>
<Panel title="Setup explanation"><p className="text-sm leading-relaxed text-slate-300">{active ? `${active.side === 'BUY' ? 'CALL' : 'PUT'} setup was generated by ${names[active.strategy]}. ${reasons.join('. ')}. Planned underlying entry ${num(active.entryPrice)}, stop ${num(active.stopLoss)}. ${invalidations.join('. ')}.` : v?.noTradeReasons.length ? `The setup is inactive. ${v.noTradeReasons.slice(0, 4).join('. ')}. Wait for the missing conditions before considering an entry.` : 'The backend is checking market data, session, structure, confirmation and risk.'}</p><p className="mt-3 text-xs text-slate-500">Deterministic explanation from backend facts. Setup score describes rule alignment and does not promise profitability.</p></Panel><Panel title="No-trade filter"><div className="flex gap-3"><AlertTriangle size={20} className="shrink-0 text-amber-300"/><div><p className="text-sm font-semibold">{stale ? 'MARKET DATA DELAYED' : v?.noTradeReasons.length ? 'NO NEW TRADE' : 'ALL MANDATORY FILTERS PASSED'}</p><p className="mt-1 text-xs text-slate-400">{stale ? 'New trades disabled until fresh broker data resumes.' : v?.noTradeReasons.join(' · ')}</p></div></div></Panel>
<Panel title="Live trade progress"><p className="mb-4 text-xs text-slate-400">WAITING → ENTRY → RUNNING → T1 → T2 → EXIT</p>{active ? <><p className="font-mono text-xs text-cyan-300">Signal {active.id}</p><div className="mt-4 flex flex-wrap gap-3">{active.events.map(e => <span key={e.type} className="rounded-lg bg-sky-400/10 px-3 py-2 text-xs text-sky-200">{e.type.replaceAll('_', ' ')} · {num(e.executedPrice)} · {time(e.eventTime)}</span>)}</div><p className="mt-3 text-xs text-slate-500">Cutoff {v?.session.cutoff} · Square-off {v?.session.squareOff} IST. Progress tracks the underlying signal.</p></> : <p className="text-sm text-slate-400">No active Nifty signal.</p>}</Panel>
<Panel title="Strategy performance & backtesting"><div className="mb-5 flex flex-wrap items-end gap-3"><label className="text-xs text-slate-400">From<input type="date" value={from} onChange={e => setFrom(e.target.value)} className="ml-2 rounded bg-slate-900 p-2"/></label><label className="text-xs text-slate-400">To<input type="date" value={to} onChange={e => setTo(e.target.value)} className="ml-2 rounded bg-slate-900 p-2"/></label><select aria-label="Strategy filter" value={filter} onChange={e => setFilter(e.target.value)} className="rounded bg-slate-900 p-2 text-xs"><option value="">All strategies</option>{Object.entries(names).map(([k, n]) => <option key={k} value={k}>{n}</option>)}</select><select aria-label="Direction filter" value={side} onChange={e => setSide(e.target.value)} className="rounded bg-slate-900 p-2 text-xs"><option value="">Both directions</option><option value="BUY">Long / Call</option><option value="SELL">Short / Put</option></select><select aria-label="Regime filter" value={regime} onChange={e => setRegime(e.target.value)} className="rounded bg-slate-900 p-2 text-xs"><option value="">All regimes</option>{['BULLISH', 'STRONG BULLISH', 'BEARISH', 'STRONG BEARISH'].map(r => <option key={r}>{r}</option>)}</select><select aria-label="Window filter" value={windowFilter} onChange={e => setWindowFilter(e.target.value)} className="rounded bg-slate-900 p-2 text-xs"><option value="">All windows</option><option value="MORNING">Morning</option><option value="AFTERNOON">Afternoon</option></select><button disabled={!from || !to || backtest.isPending} onClick={() => backtest.mutate()} className="primary-button disabled:opacity-40">{backtest.isPending ? 'Backtesting…' : 'Run backtest'}</button></div>{backtest.error && <p role="alert" className="mb-3 text-sm text-rose-300">{backtest.error.message}</p>}<PerformanceTable data={backtest.data ?? filteredPerformance.data ?? v?.performance}/></Panel>
<Panel title="Signal history"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr>{['Signal / generated', 'Strategy', 'Direction', 'Entry', 'SL', 'T1 / T2 / T3', 'Score', 'Status'].map(h => <th key={h} className="pb-3 pr-4">{h}</th>)}</tr></thead><tbody>{history.data?.map(s => <tr key={s.id} className="border-t border-white/5"><td className="py-3 pr-4"><span className="block font-mono text-sky-300">{s.id}</span>{time(s.signalGeneratedAt)}</td><td className="pr-4">{names[s.strategy]}</td><td className="pr-4">{s.side === 'BUY' ? 'CALL' : 'PUT'}</td><td className="pr-4">{num(s.entryExecutedPrice ?? s.entryPrice)}</td><td className="pr-4">{num(s.stopLoss)}</td><td className="pr-4">{num(s.target1)} / {num(s.target2)} / {num(s.target3)}</td><td className="pr-4">{s.aiScore}/100</td><td>{s.status.replaceAll('_', ' ')}</td></tr>)}</tbody></table>{!history.data?.length && <p className="py-8 text-center text-sm text-slate-500">No Nifty signals in this period. Setups are saved only after mandatory filters pass.</p>}</div></Panel>
</div>;
}
function PerformanceTable({ data }: {
  data: Performance | undefined;
}) { return <>{data?.frequency && <div className="mb-4 grid gap-4 sm:grid-cols-3">{data.frequency.map(f=><div key={f.strategy} className="text-xs text-slate-400"><p>{names[f.strategy]} · {f.sessionDays} sessions</p><p>Average setups/day: {num(f.averageSetupsPerDay)}</p><p>Average trades/day: {num(f.averageTradesPerDay)}</p></div>)}</div>}<p className="mb-4 text-xs text-slate-500">{data?.label ?? 'Waiting for observations'}</p><div className="grid gap-3 md:grid-cols-3">{data?.strategies.map(s => <div key={s.strategy} className="rounded-xl border border-white/10 p-4"><h3 className="text-sm font-semibold">{names[s.strategy]}</h3><p className="mt-2 text-xs text-slate-400">Sample size {s.sampleSize} · minimum {s.minimumSamples}</p>{s.sufficient ? <div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(s).filter(([k]) => !['strategy', 'sampleSize', 'sufficient', 'minimumSamples'].includes(k)).map(([k, x]) => <Metric key={k} label={k.replace(/([A-Z])/g, ' $1')} value={num(x as number | null)}/>)}</div> : <p className="mt-4 text-xs text-amber-300">Insufficient sample size. Performance estimates withheld.</p>}</div>)}</div></>; }
export function NiftySettings({ settings, onSaved }: {
  settings: Settings;
  onSaved: () => void;
}) { const [draft, setDraft] = useState(settings); const save = useMutation({ mutationFn: () => api<Settings>('/nifty/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(draft) }), onSuccess: onSaved }); return <Panel title="Nifty risk & session settings"><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-4">{Object.entries(draft).filter(([k, v]) => k !== 'strikeOffset' && k !== 'capital' && (typeof v === 'number' || typeof v === 'string')).map(([k, v]) => <label key={k} className="text-xs text-slate-400">{k.replace(/([A-Z])/g, ' $1')}{k === 'minimumScore' ? <select value={draft.minimumScore} onChange={e=>setDraft(old=>({...old,minimumScore:Number(e.target.value)}))} className="mt-2 block w-full rounded-lg bg-slate-950 p-2">{[60,65,70,75,80].map(score=><option key={score}>{score}</option>)}</select> : <input type={typeof v === 'number' ? 'number' : 'time'} step="any" value={v as number | string} onChange={e => setDraft(old => ({ ...old, [k]: typeof v === 'number' ? Number(e.target.value) : e.target.value }))} className="mt-2 block w-full rounded-lg border border-white/10 bg-slate-950 p-2 text-white"/>}</label>)}</div><div className="mt-4 flex flex-wrap gap-4 text-xs">{['requireHistoricalPerformance', 'moveToBreakeven', 'trailAfterT2'].map(k => <label key={k}><input type="checkbox" checked={draft[k as 'moveToBreakeven']} onChange={e => setDraft(old => ({ ...old, [k]: e.target.checked }))}/> {k.replace(/([A-Z])/g, ' $1')}</label>)}</div><div className="mt-4 flex flex-wrap gap-4 text-xs">{Object.entries(names).map(([k, n]) => <label key={k}><input type="checkbox" checked={draft.enabledStrategies.includes(k)} onChange={() => setDraft(old => ({ ...old, enabledStrategies: old.enabledStrategies.includes(k) ? old.enabledStrategies.filter(v => v !== k) : [...old.enabledStrategies, k] }))}/> {n}</label>)}</div><div className="mt-4 flex flex-wrap gap-4">{draft.windows.map(([start, end], i) => <div key={i} className="text-xs text-slate-400">Window {i + 1} <input aria-label={`Window ${i + 1} start`} type="time" value={start} onChange={e => setDraft(old => ({ ...old, windows: old.windows.map((w, j) => i === j ? [e.target.value, w[1]] : w) }))} className="rounded bg-slate-950 p-2"/> – <input aria-label={`Window ${i + 1} end`} type="time" value={end} onChange={e => setDraft(old => ({ ...old, windows: old.windows.map((w, j) => i === j ? [w[0], e.target.value] : w) }))} className="rounded bg-slate-950 p-2"/></div>)}</div>{save.error && <p role="alert" className="mt-4 text-sm text-rose-300">{save.error.message}</p>}<button onClick={() => save.mutate()} disabled={save.isPending} className="primary-button mt-5">Save settings</button></Panel>; }
export function NiftySettingsPage({ session }: {
  session: string;
}) { const client = useQueryClient(); const q = useQuery({ queryKey: ['nifty', 'settings', session], queryFn: () => api<Settings>('/nifty/settings'), enabled: !!session }); return q.data ? <NiftySettings settings={q.data} onSaved={() => void client.invalidateQueries({ queryKey: ['nifty'] })}/> : <Panel title="Nifty settings"><p className="text-sm text-slate-400">{q.error?.message ?? (session ? 'Loading configuration…' : 'Connect Upstox to configure Nifty.')}</p></Panel>; }

export function NiftyWorkspace({ session }: { session: string }) {
  const [tab,setTab] = useState('analysis');
  return <div className="space-y-5"><div role="tablist" aria-label="Nifty workspace" className="flex gap-3">{[['analysis','NIFTY ANALYSIS'],['demo','DEMO ACCOUNT']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)} className={`rounded-lg px-5 py-3 text-sm font-semibold ${tab===key?'bg-cyan-400/15 text-cyan-200':'text-slate-400'}`}>{label}</button>)}</div><div hidden={tab!=='analysis'}><NiftyAnalysis session={session}/></div>{tab==='demo' && <NiftyDemoAccount session={session}/>}</div>;
}
