'use client';

import { useQuery } from '@tanstack/react-query';
import { Activity, ChevronDown, Copy, Download, FileText, RefreshCw, Search, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';

type Event = { id?: string; type: string; eventTime: string; executedPrice: number; profitPercent: number; holdingMinutes: number };
type Signal = { id: string; signalTime: string; updatedAt: string; instrumentKey: string; stockName: string; symbol: string; sector: string; strategy: string; timeframe: string; side: 'BUY' | 'SELL'; status: string; entryPrice: number; currentPrice: number; stopLoss: number; target1: number; target2: number; target3: number; confidence: number; aiScore: number; profitPercent?: number | null; holdingMinutes?: number | null; completedAt?: string | null; events: Event[] };
type Hour = { label: string; signals: number; wins: number; losses: number; winRate: number; averageProfit: number; totalProfit: number };
type Loss = { signalId: string; stock: string; symbol: string; side: 'BUY' | 'SELL'; entry: number; exit: number; lossPercent: number; holdingTime: number; exitReason: string; confidence: number; aiScore: number; strategy: string; time: string };
type DashboardData = { signals: Signal[]; summary: { todaySignals: number; winningTrades: number; losingTrades: number; winRate: number; averageProfit: number; averageLoss: number; stopLossHit: number; bestTrade: Signal | null; worstTrade: Signal | null }; analytics: { compactFlow: Array<{ key: string; label: string; count: number }>; conversions: Array<{ key: string; label: string; percentage: number }>; health: Array<{ key: string; label: string; value: number; suffix: string }> }; bestTradingHours: { hours: Hour[]; bestHour: string | null; worstHour: string | null; mostProfitableHour: string | null; mostActiveHour: string | null }; losingTradeBreakdown: { total: number; categories: Array<{ reason: string; count: number }>; trades: Loss[] }; marketWindow: { start: string; end: string } };
type StopLossData = { summary: { stopLossTotal: number; immediateStopLoss: number; reachedEntryBeforeStopLoss: number; reachedTarget1BeforeStopLoss: number; reachedTarget2BeforeStopLoss: number; reachedTarget3BeforeStopLoss: number; averageMaximumProfitBeforeStopLoss: number; averageTimeUntilStopLoss: number } };
type PaperData = { executionDecisions?: Array<{ signalId: string; symbol: string; decision: string; reason: string; confidence: number; availableCapital: number }> };

const cash = (value: number) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const clock = (value?: string | null) => value ? new Date(value).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '—';
const percent = (value: number) => `${value >= 0 ? '+' : ''}${Number(value || 0).toFixed(2)}%`;
const statusRank: Record<string, number> = { WAITING: 0, ENTRY_TRIGGERED: 1, RUNNING: 2, TARGET1_HIT: 3, TARGET2_HIT: 4, TARGET3_HIT: 5, COMPLETED: 6 };

function Panel({ title, eyebrow, children, open = true }: { title: string; eyebrow?: string; children: React.ReactNode; open?: boolean }) {
  return <details open={open} className="group overflow-hidden rounded-2xl border border-slate-800 bg-[#0b1220]/90 shadow-[0_18px_60px_rgba(0,0,0,.2)]"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 border-b border-slate-800/80 px-5 py-4"><div>{eyebrow && <p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-400">{eyebrow}</p>}<h2 className="mt-1 text-base font-black text-white">{title}</h2></div><ChevronDown className="h-4 w-4 text-slate-500 transition group-open:rotate-180" /></summary>{children}</details>;
}
function Stat({ label, value, tone = 'text-white' }: { label: string; value: string | number; tone?: string }) {
  return <div className="rounded-xl border border-slate-800 bg-slate-950/50 px-3 py-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-1 text-lg font-black ${tone}`}>{value}</p></div>;
}
function Bars({ items, color = 'bg-cyan-400' }: { items: Array<{ label: string; value: number; detail?: string }>; color?: string }) {
  const maximum = Math.max(1, ...items.map((item) => item.value));
  return <div className="space-y-3">{items.map((item) => <div key={item.label}><div className="mb-1 flex justify-between text-[10px]"><span className="font-bold text-slate-300">{item.label}</span><span className="text-slate-500">{item.detail ?? item.value}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full transition-all duration-700 ${color}`} style={{ width: `${item.value / maximum * 100}%` }} /></div></div>)}</div>;
}
function performanceRows(signals: Signal[], key: 'sector' | 'strategy') {
  const groups = new Map<string, Signal[]>();
  for (const signal of signals) groups.set(signal[key] || 'Unknown', [...(groups.get(signal[key] || 'Unknown') ?? []), signal]);
  return [...groups].map(([name, items]) => { const completed = items.filter((item) => item.completedAt); const wins = completed.filter((item) => Number(item.profitPercent) > 0); const losses = completed.filter((item) => Number(item.profitPercent) < 0); return { name, signals: items.length, wins: wins.length, losses: losses.length, winRate: completed.length ? wins.length / completed.length * 100 : 0, averageProfit: completed.length ? completed.reduce((sum, item) => sum + Number(item.profitPercent ?? 0), 0) / completed.length : 0 }; }).sort((left, right) => right.winRate - left.winRate || right.signals - left.signals);
}

export function SignalHistoryRedesign() {
  const history = useQuery({ queryKey: ['ai-signal-history'], queryFn: () => api<DashboardData>('/signal-history'), retry: false, refetchInterval: 15_000 });
  const stops = useQuery({ queryKey: ['redesign-stop-loss-today'], queryFn: () => api<StopLossData>('/signal-history/analysis/stop-loss-journeys?period=today'), retry: false, staleTime: 60_000 });
  const paper = useQuery({ queryKey: ['demo-paper-trading'], queryFn: () => api<PaperData>('/paper-trading'), retry: false, staleTime: 15_000 });
  const [selected, setSelected] = useState<Signal | null>(null);
  const [online, setOnline] = useState(true);
  const [filters, setFilters] = useState({ stock: '', sector: 'ALL', side: 'ALL', strategy: 'ALL', confidence: 0, aiScore: 0, target: 'ALL', result: 'ALL', holding: 0 });
  useEffect(() => { const sync = () => setOnline(navigator.onLine); window.addEventListener('online', sync); window.addEventListener('offline', sync); return () => { window.removeEventListener('online', sync); window.removeEventListener('offline', sync); }; }, []);
  const data = history.data;
  const signals = data?.signals ?? [];
  const completed = signals.filter((signal) => signal.completedAt);
  const winners = [...completed].filter((signal) => Number(signal.profitPercent) > 0).sort((left, right) => Number(right.profitPercent) - Number(left.profitPercent));
  const losers = [...completed].filter((signal) => Number(signal.profitPercent) < 0).sort((left, right) => Number(left.profitPercent) - Number(right.profitPercent));
  const sectors = performanceRows(signals, 'sector');
  const strategies = performanceRows(signals, 'strategy');
  const bestStrategy = strategies[0];
  const buys = signals.filter((signal) => signal.side === 'BUY').length;
  const sells = signals.length - buys;
  const averageConfidence = signals.length ? signals.reduce((sum, signal) => sum + signal.confidence, 0) / signals.length : 0;
  const scores = signals.map((signal) => signal.aiScore);
  const confidences = signals.map((signal) => signal.confidence);
  const flow = Object.fromEntries((data?.analytics.compactFlow ?? []).map((item) => [item.key, item.count]));
  const distribution = [{ label: 'BUY', value: buys }, { label: 'SELL', value: sells }, ...(data?.analytics.compactFlow ?? []).map((item) => ({ label: item.label, value: item.count }))];
  const confidenceBars = [{ label: '95–100', min: 95, max: 101 }, { label: '90–95', min: 90, max: 95 }, { label: '85–90', min: 85, max: 90 }, { label: '80–85', min: 80, max: 85 }, { label: 'Below 80', min: -Infinity, max: 80 }].map((band) => ({ label: band.label, value: signals.filter((signal) => signal.confidence >= band.min && signal.confidence < band.max).length }));
  const recommendation = buys > sells * 1.15 ? 'Focus on BUY continuation setups.' : sells > buys * 1.15 ? 'Focus on SELL continuation setups.' : 'Market signals are balanced; prioritize confirmed setups.';
  const latest = signals.reduce((value, signal) => Math.max(value, new Date(signal.updatedAt).getTime()), 0);
  const elapsedSeconds = data ? Math.max(1, (Date.now() - new Date(data.marketWindow.start).getTime()) / 1000) : 1;
  const filtered = signals.filter((signal) => (!filters.stock || `${signal.stockName} ${signal.symbol}`.toLowerCase().includes(filters.stock.toLowerCase())) && (filters.sector === 'ALL' || signal.sector === filters.sector) && (filters.side === 'ALL' || signal.side === filters.side) && (filters.strategy === 'ALL' || signal.strategy === filters.strategy) && signal.confidence >= filters.confidence && signal.aiScore >= filters.aiScore && (filters.target === 'ALL' || signal.status === filters.target) && (filters.result === 'ALL' || filters.result === 'PROFIT' && Number(signal.profitPercent) > 0 || filters.result === 'LOSS' && Number(signal.profitPercent) < 0) && Number(signal.holdingMinutes ?? 0) >= filters.holding);
  const missed = (paper.data?.executionDecisions ?? []).filter((decision) => decision.decision === 'SKIPPED' && signals.some((signal) => signal.id === decision.signalId && statusRank[signal.status] >= 5));
  const download = (filename: string, text: string, mime = 'text/plain') => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: mime })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); };
  const csv = () => download('ai-signal-history-today.csv', ['Stock,Side,Status,Entry,Current,Profit,Confidence,AI Score,Strategy', ...signals.map((signal) => [signal.symbol, signal.side, signal.status, signal.entryPrice, signal.currentPrice, signal.profitPercent ?? '', signal.confidence, signal.aiScore, signal.strategy].join(','))].join('\n'), 'text/csv');
  const report = `Today's AI Signal Report\nSignals: ${data?.summary.todaySignals ?? 0}\nRunning: ${flow.flow_running ?? 0}\nCompleted: ${flow.flow_completed ?? 0}\nWin Rate: ${(data?.summary.winRate ?? 0).toFixed(1)}%\nBest Hour: ${data?.bestTradingHours.bestHour ?? '—'}\nRecommendation: ${recommendation}`;
  if (history.isLoading) return <div className="grid min-h-80 place-items-center"><Activity className="h-6 w-6 animate-pulse text-cyan-300" /></div>;
  if (!data) return <div className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-5 text-sm text-rose-300">Today&apos;s institutional dashboard could not load.</div>;
  const sticky = [["Today's Signals", data.summary.todaySignals], ['Running', flow.flow_running ?? 0], ['Waiting', flow.flow_waiting_now ?? 0], ['Target1', flow.flow_target1 ?? 0], ['Target2', flow.flow_target2 ?? 0], ['Target3', flow.flow_target3 ?? 0], ['Completed', flow.flow_completed ?? 0], ['Winning', data.summary.winningTrades], ['Losing', data.summary.losingTrades], ['Win Rate', `${data.summary.winRate.toFixed(1)}%`]];
  return <div className="space-y-4"><div className="sticky top-0 z-40 -mx-1 overflow-x-auto rounded-xl border border-slate-700/80 bg-[#080e19]/95 p-2 shadow-2xl backdrop-blur-xl"><div className="flex min-w-max items-center gap-1">{sticky.map(([label, value]) => <div key={String(label)} className="min-w-24 rounded-lg border border-slate-800 bg-slate-950/70 px-3 py-2"><p className="text-[8px] font-black uppercase text-slate-500">{label}</p><p className="mt-0.5 text-sm font-black text-white">{value}</p></div>)}<div className="min-w-28 px-3"><p className="text-[8px] font-black uppercase text-slate-500">Market Status</p><p className="mt-1 text-xs font-black text-emerald-300">● LIVE SESSION</p></div><div className="min-w-28 px-3"><p className="text-[8px] font-black uppercase text-slate-500">Last Update</p><p className="mt-1 text-xs font-black text-cyan-300">{clock(latest ? new Date(latest).toISOString() : null)}</p></div></div></div>
    <section className="overflow-hidden rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/10 via-[#0c1424] to-cyan-500/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.24em] text-violet-300">AI MARKET SUMMARY</p><h2 className="mt-1 text-2xl font-black text-white">Today&apos;s Market <span className={buys >= sells ? 'text-emerald-300' : 'text-rose-300'}>{buys >= sells ? 'Bullish' : 'Bearish'}</span></h2></div><p className="max-w-md rounded-xl border border-violet-400/20 bg-violet-400/[.07] px-4 py-3 text-sm font-bold text-violet-200">{recommendation}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><Stat label="Best Strategy" value={bestStrategy ? `${bestStrategy.name} · ${bestStrategy.winRate.toFixed(0)}%` : '—'} tone="text-violet-300" /><Stat label="Best Trading Hour" value={data.bestTradingHours.bestHour ?? '—'} tone="text-cyan-300" /><Stat label="Highest Confidence" value={`${Math.max(0, ...confidences)}%`} /><Stat label="Average Confidence" value={`${averageConfidence.toFixed(1)}%`} /><Stat label="Highest Profit" value={percent(Number(winners[0]?.profitPercent ?? 0))} tone="text-emerald-300" /><Stat label="Worst Trade" value={percent(Number(losers[0]?.profitPercent ?? 0))} tone="text-rose-300" /><Stat label="Signals Generated" value={data.summary.todaySignals} /><Stat label="Signals Running" value={flow.flow_running ?? 0} tone="text-sky-300" /><Stat label="Signals Completed" value={flow.flow_completed ?? 0} tone="text-emerald-300" /><Stat label="BUY / SELL" value={`${buys} / ${sells}`} /></div></section>
    <div className="flex flex-wrap gap-2 rounded-xl border border-slate-800 bg-[#0b1220] p-3"><button onClick={() => void history.refetch()} className="primary-button flex items-center gap-2"><RefreshCw className="h-4 w-4" />Refresh</button><button onClick={csv} className="primary-button flex items-center gap-2"><Download className="h-4 w-4" />Export CSV</button><button onClick={() => window.print()} className="primary-button flex items-center gap-2"><FileText className="h-4 w-4" />Export PDF</button><button onClick={() => void navigator.clipboard.writeText(report)} className="primary-button flex items-center gap-2"><Copy className="h-4 w-4" />Copy Report</button><button onClick={() => download('today-ai-report.txt', report)} className="primary-button">Today&apos;s Report</button></div>
    <Panel title="Overview & Distribution" eyebrow="MARKET STRUCTURE"><div className="grid gap-5 p-5 xl:grid-cols-3"><div><h3 className="mb-4 text-xs font-black text-white">Signal Distribution</h3><Bars items={distribution.map((item) => ({ ...item, detail: String(item.value) }))} /></div><div><h3 className="mb-4 text-xs font-black text-white">Confidence Distribution</h3><Bars items={confidenceBars} color="bg-violet-400" /></div><div><h3 className="mb-4 text-xs font-black text-white">AI Score Analytics</h3><div className="grid grid-cols-2 gap-3"><Stat label="Average AI Score" value={scores.length ? (scores.reduce((sum, score) => sum + score, 0) / scores.length).toFixed(1) : '0'} tone="text-violet-300" /><Stat label="Highest AI Score" value={Math.max(0, ...scores)} /><Stat label="Lowest AI Score" value={scores.length ? Math.min(...scores) : 0} /><Stat label="Average Confidence" value={`${averageConfidence.toFixed(1)}%`} /><Stat label="Highest Confidence" value={`${Math.max(0, ...confidences)}%`} /><Stat label="Lowest Confidence" value={`${confidences.length ? Math.min(...confidences) : 0}%`} /></div></div></div></Panel>
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Best Trading Hours" eyebrow="HOURLY PERFORMANCE"><div className="space-y-2 p-4">{data.bestTradingHours.hours.map((hour, index) => <div key={hour.label} className={`grid grid-cols-5 gap-2 rounded-xl border p-3 text-xs ${index === 0 ? 'border-emerald-400/40 bg-emerald-400/10' : 'border-slate-800 bg-slate-950/40'}`}><b className="text-white">{hour.label}</b><span>{hour.signals} signals</span><span className="text-emerald-300">{hour.wins} wins</span><span className="text-rose-300">{hour.losses} losses</span><span className="font-black text-cyan-300">{hour.winRate.toFixed(1)}%</span></div>)}</div></Panel><Panel title="Live AI Health" eyebrow="SYSTEM STATUS"><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-4"><Stat label="Scanner" value={latest && Date.now() - latest < 120_000 ? 'Running' : 'Idle'} tone="text-emerald-300" /><Stat label="API" value={history.isSuccess ? 'Connected' : 'Unavailable'} tone="text-emerald-300" /><Stat label="Database" value={history.isSuccess ? 'Connected' : 'Unavailable'} tone="text-emerald-300" /><Stat label="WebSocket" value={online ? 'Connected' : 'Offline'} tone={online ? 'text-emerald-300' : 'text-rose-300'} /><Stat label="Market" value="Open" tone="text-emerald-300" /><Stat label="Latency" value={history.fetchStatus === 'fetching' ? 'Syncing' : 'Live'} /><Stat label="Signals/sec" value={(signals.length / elapsedSeconds).toFixed(3)} /><Stat label="Last Scan" value={clock(latest ? new Date(latest).toISOString() : null)} /></div></Panel></div>
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Sector Performance" eyebrow="TODAY BY SECTOR"><div className="max-h-80 overflow-auto p-4"><Bars items={sectors.map((item) => ({ label: item.name, value: item.signals, detail: `${item.signals} · ${item.winRate.toFixed(0)}% WR · ${percent(item.averageProfit)}` }))} color="bg-sky-400" /></div></Panel><Panel title="Strategy Performance" eyebrow="TODAY BY STRATEGY"><div className="max-h-80 overflow-auto p-4"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr>{['Strategy', 'Signals', 'Wins', 'Losses', 'Win Rate', 'Avg Profit'].map((item) => <th key={item} className="px-2 py-2">{item}</th>)}</tr></thead><tbody>{strategies.map((item) => <tr key={item.name} className="border-t border-slate-800"><td className="px-2 py-3 font-bold text-white">{item.name}</td><td>{item.signals}</td><td className="text-emerald-300">{item.wins}</td><td className="text-rose-300">{item.losses}</td><td>{item.winRate.toFixed(1)}%</td><td>{percent(item.averageProfit)}</td></tr>)}</tbody></table></div></Panel></div>
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Top Winners" eyebrow="BEST COMPLETED TRADES"><div className="max-h-80 overflow-auto p-4"><table className="w-full text-left text-xs"><tbody>{winners.slice(0, 10).map((signal) => <tr key={signal.id} onClick={() => setSelected(signal)} className="cursor-pointer border-t border-slate-800 hover:bg-slate-800/40"><td className="px-2 py-3 font-black text-white">{signal.symbol}</td><td className="text-emerald-300">{percent(Number(signal.profitPercent))}</td><td>{signal.holdingMinutes ?? 0} min</td><td>{signal.strategy}</td><td>{signal.aiScore}</td><td>{signal.confidence}%</td></tr>)}</tbody></table></div></Panel><Panel title="Biggest Losers" eyebrow="LOSS REVIEW"><div className="max-h-80 overflow-auto p-4"><table className="w-full text-left text-xs"><tbody>{losers.slice(0, 10).map((signal) => { const detail = data.losingTradeBreakdown.trades.find((item) => item.signalId === signal.id); return <tr key={signal.id} onClick={() => setSelected(signal)} className="cursor-pointer border-t border-slate-800 hover:bg-slate-800/40"><td className="px-2 py-3 font-black text-white">{signal.symbol}</td><td className="text-rose-300">{percent(Number(signal.profitPercent))}</td><td>{detail?.exitReason ?? 'Loss Exit'}</td><td>{cash(signal.stopLoss)}</td><td>{signal.holdingMinutes ?? 0} min</td></tr>; })}</tbody></table></div></Panel></div>
    <Panel title="Losing Trade Analysis" eyebrow="ROOT CAUSE REVIEW"><div className="grid gap-3 p-4 sm:grid-cols-3 lg:grid-cols-7">{data.losingTradeBreakdown.categories.map((item) => <Stat key={item.reason} label={item.reason} value={item.count} tone="text-rose-300" />)}<Stat label="Total" value={data.losingTradeBreakdown.total} /></div><div className="max-h-96 overflow-auto border-t border-slate-800"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="sticky top-0 bg-[#0b1220] text-slate-500"><tr>{['Stock', 'Side', 'Entry', 'Exit', 'Loss %', 'Holding', 'Exit Reason', 'Confidence', 'AI Score', 'Strategy'].map((item) => <th key={item} className="px-3 py-3">{item}</th>)}</tr></thead><tbody>{data.losingTradeBreakdown.trades.map((loss) => <tr key={loss.signalId} className="border-t border-slate-800"><td className="px-3 py-3 font-black text-white">{loss.stock}</td><td>{loss.side}</td><td>{cash(loss.entry)}</td><td>{cash(loss.exit)}</td><td className="text-rose-300">-{loss.lossPercent.toFixed(2)}%</td><td>{loss.holdingTime} min</td><td>{loss.exitReason}</td><td>{loss.confidence}%</td><td>{loss.aiScore}</td><td>{loss.strategy}</td></tr>)}</tbody></table></div></Panel>
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Stop Loss Analysis" eyebrow="RISK OUTCOMES"><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-3">{stops.data ? Object.entries({ 'Stop Loss Hit': stops.data.summary.stopLossTotal, 'Average Loss': `${Math.abs(data.summary.averageLoss).toFixed(2)}%`, 'Average Holding': `${stops.data.summary.averageTimeUntilStopLoss.toFixed(0)} min`, 'Recovery Rate': `${(data.analytics.health.find((item) => item.key === 'health_recovery')?.value ?? 0).toFixed(1)}%`, 'Immediate Stop Loss': stops.data.summary.immediateStopLoss, 'Reached Entry Before SL': stops.data.summary.reachedEntryBeforeStopLoss, 'Reached Target1 Before SL': stops.data.summary.reachedTarget1BeforeStopLoss, 'Reached Target2 Before SL': stops.data.summary.reachedTarget2BeforeStopLoss, 'Reached Target3 Before SL': stops.data.summary.reachedTarget3BeforeStopLoss }).map(([label, value]) => <Stat key={label} label={label} value={value} />) : <p className="text-xs text-slate-500">Loading stop-loss analytics…</p>}</div></Panel><Panel title="Missed Opportunities" eyebrow="TARGET 3 · NOT TRADED"><div className="space-y-2 p-4">{missed.map((item) => <div key={`${item.signalId}-${item.reason}`} className="grid grid-cols-4 gap-3 rounded-lg border border-amber-400/15 bg-amber-400/[.05] p-3 text-xs"><b className="text-white">{item.symbol}</b><span>{item.reason}</span><span>{item.confidence}% confidence</span><span>{cash(item.availableCapital)} capital</span></div>)}{!missed.length && <p className="py-8 text-center text-sm text-slate-500">No verified Target 3 missed opportunities today.</p>}</div></Panel></div>
    <Panel title="Signals" eyebrow="SEARCH · FILTER · INVESTIGATE"><div className="grid gap-2 border-b border-slate-800 p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-600" /><input value={filters.stock} onChange={(event) => setFilters({ ...filters, stock: event.target.value })} placeholder="Search stock" className="w-full rounded-lg border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-xs text-white" /></label>{([['sector', ['ALL', ...new Set(signals.map((signal) => signal.sector))]], ['side', ['ALL', 'BUY', 'SELL']], ['strategy', ['ALL', ...new Set(signals.map((signal) => signal.strategy))]], ['target', ['ALL', 'WAITING', 'ENTRY_TRIGGERED', 'RUNNING', 'TARGET1_HIT', 'TARGET2_HIT', 'TARGET3_HIT', 'COMPLETED']], ['result', ['ALL', 'PROFIT', 'LOSS']]] as const).map(([key, values]) => <select key={key} value={filters[key]} onChange={(event) => setFilters({ ...filters, [key]: event.target.value })} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-xs text-white">{[...values].map((value) => <option key={value}>{value}</option>)}</select>)}{([['confidence', 'Minimum confidence'], ['aiScore', 'Minimum AI score'], ['holding', 'Minimum holding minutes']] as const).map(([key, label]) => <input key={key} type="number" value={filters[key]} onChange={(event) => setFilters({ ...filters, [key]: Number(event.target.value) })} placeholder={label} title={label} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-xs text-white" />)}</div><div className="max-h-[520px] overflow-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="sticky top-0 bg-[#0b1220] text-slate-500"><tr>{['Stock', 'Side', 'Sector', 'Strategy', 'Status', 'Confidence', 'AI Score', 'Entry', 'Current', 'P/L', 'Holding'].map((item) => <th key={item} className="px-3 py-3">{item}</th>)}</tr></thead><tbody>{filtered.map((signal) => <tr key={signal.id} onClick={() => setSelected(signal)} className="cursor-pointer border-t border-slate-800 hover:bg-cyan-400/[.04]"><td className="px-3 py-3"><b className="block text-white">{signal.stockName}</b><span className="text-slate-500">{signal.symbol}</span></td><td className={signal.side === 'BUY' ? 'text-emerald-300' : 'text-rose-300'}>{signal.side}</td><td>{signal.sector}</td><td>{signal.strategy}</td><td className="text-cyan-300">{signal.status.replaceAll('_', ' ')}</td><td>{signal.confidence}%</td><td>{signal.aiScore}</td><td>{cash(signal.entryPrice)}</td><td>{cash(signal.currentPrice)}</td><td className={Number(signal.profitPercent) >= 0 ? 'text-emerald-300' : 'text-rose-300'}>{signal.profitPercent == null ? '—' : percent(signal.profitPercent)}</td><td>{signal.holdingMinutes ?? 0} min</td></tr>)}</tbody></table></div></Panel>
    {selected && <><button aria-label="Close stock details" onClick={() => setSelected(null)} className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" /><aside className="fixed inset-y-0 right-0 z-[60] w-full max-w-xl overflow-y-auto border-l border-slate-700 bg-[#080e19] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-violet-300">STOCK DETAILS</p><h2 className="mt-1 text-2xl font-black text-white">{selected.stockName}</h2><p className="text-sm text-slate-500">{selected.symbol} · {selected.side} · {selected.strategy}</p></div><button onClick={() => setSelected(null)} className="rounded-lg border border-slate-700 p-2 text-slate-400"><X className="h-4 w-4" /></button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><Stat label="Entry" value={cash(selected.entryPrice)} /><Stat label="Stop Loss" value={cash(selected.stopLoss)} tone="text-rose-300" /><Stat label="Target 1" value={cash(selected.target1)} /><Stat label="Target 2" value={cash(selected.target2)} /><Stat label="Target 3" value={cash(selected.target3)} /><Stat label="Profit" value={selected.profitPercent == null ? 'Running' : percent(selected.profitPercent)} tone={Number(selected.profitPercent) >= 0 ? 'text-emerald-300' : 'text-rose-300'} /></div><div className="mt-6"><h3 className="text-xs font-black uppercase text-slate-400">Timeline & Decision Log</h3><div className="mt-3 space-y-2">{selected.events.map((event, index) => <div key={`${event.type}-${index}`} className="flex items-center justify-between rounded-lg border border-slate-800 bg-slate-950/50 p-3 text-xs"><div><b className="text-white">{event.type.replaceAll('_', ' ')}</b><p className="mt-1 text-slate-500">{clock(event.eventTime)}</p></div><div className="text-right"><p>{cash(event.executedPrice)}</p><p className={event.profitPercent >= 0 ? 'text-emerald-300' : 'text-rose-300'}>{percent(event.profitPercent)}</p></div></div>)}</div></div><div className="mt-6 grid gap-3"><Stat label="AI Reason" value="Signal rationale retained in the analysis workspace" /><Stat label="Indicators" value={`Confidence ${selected.confidence}% · AI Score ${selected.aiScore}`} /><Stat label="Price Journey" value={`${cash(selected.entryPrice)} → ${cash(selected.currentPrice)}`} /><Stat label="Exit Reason" value={data.losingTradeBreakdown.trades.find((item) => item.signalId === selected.id)?.exitReason ?? (selected.completedAt ? 'Target completion' : 'Position active')} /></div></aside></>}
  </div>;
}
