'use client';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Volume2, VolumeX } from 'lucide-react';
import { useEffect, useState } from 'react';
import { paperTradingService } from '../lib/trading-services';
import type { VoiceCenterResponse, VoiceSettings } from './voice-alert-center';
const LANGUAGES = [['en-IN', 'English (India)'], ['en-US', 'English (US)'], ['hi-IN', 'Hindi']] as const;
export function VoiceAlertSettings({ session }: { session: string }) {
  const client = useQueryClient();
  const center = useQuery({ queryKey: ['paper-voice-alerts'], queryFn: () => paperTradingService.voiceAlerts<VoiceCenterResponse>(), enabled: Boolean(session), refetchInterval: 10_000 });
  const [settings, setSettings] = useState<VoiceSettings | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (center.data) setSettings(center.data.settings); }, [center.data]);
  if (!session) return <p className="text-sm text-amber-200">Connect Upstox to configure voice alerts.</p>;
  if (!settings) return <p className="text-sm text-slate-400">Loading voice preferences...</p>;
  const save = async () => { setSaving(true); try { await paperTradingService.updateSettings(settings); await client.invalidateQueries({ queryKey: ['paper-voice-alerts'] }); } finally { setSaving(false); } };
  const slider = (label: string, key: 'voiceVolume' | 'voiceSpeed' | 'voicePitch', min: number, max: number, step: number, suffix = '') => <label className="block border-b border-slate-800 py-5"><span className="flex justify-between text-sm font-bold text-white"><span>{label}</span><span className="text-cyan-300">{settings[key]}{suffix}</span></span><input className="mt-4 w-full accent-cyan-400" type="range" min={min} max={max} step={step} value={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: Number(event.target.value) })} /></label>;
  return <div className="space-y-6"><div><p className="section-eyebrow">DEMO TRADING NOTIFICATIONS</p><h1 className="text-3xl font-semibold text-white">Voice Alerts</h1></div><section className="grid gap-6 xl:grid-cols-[minmax(0,520px)_minmax(0,1fr)]">
    <div className="rounded-md border border-slate-800 bg-[#0b111d] p-5"><div className="flex items-center justify-between border-b border-slate-800 pb-5"><div className="flex items-center gap-3">{settings.voiceAlerts ? <Volume2 className="h-5 w-5 text-emerald-300" /> : <VolumeX className="h-5 w-5 text-slate-500" />}<div><p className="font-bold text-white">Voice Alerts</p><p className="mt-1 text-xs text-slate-500">Toast notifications remain active when speech is off.</p></div></div><button role="switch" aria-checked={settings.voiceAlerts} onClick={() => setSettings({ ...settings, voiceAlerts: !settings.voiceAlerts })} className={`relative h-7 w-12 rounded-full transition ${settings.voiceAlerts ? 'bg-emerald-500' : 'bg-slate-700'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${settings.voiceAlerts ? 'left-6' : 'left-1'}`} /></button></div>{slider('Voice Volume', 'voiceVolume', 0, 100, 1, '%')}{slider('Voice Speed', 'voiceSpeed', .5, 2, .1, 'x')}{slider('Voice Pitch', 'voicePitch', .5, 2, .1)}<label className="block py-5"><span className="text-sm font-bold text-white">Voice Language</span><select value={settings.voiceLanguage} onChange={(event) => setSettings({ ...settings, voiceLanguage: event.target.value })} className="mt-3 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white">{LANGUAGES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button onClick={() => void save()} disabled={saving} className="primary-button">{saving ? 'Saving...' : 'Save Voice Settings'}</button></div>
    <div className="rounded-md border border-slate-800 bg-[#0b111d] p-5"><h2 className="font-bold text-white">Execution Log</h2><div className="mt-4 max-h-[620px] overflow-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="sticky top-0 bg-[#0b111d] text-slate-500"><tr>{['Time', 'Trade', 'Message', 'Status'].map((label) => <th key={label} className="border-b border-slate-800 px-3 py-3">{label}</th>)}</tr></thead><tbody>{center.data?.executionLog.map((row) => <tr key={row.id} className="border-b border-slate-800/70"><td className="whitespace-nowrap px-3 py-3 text-slate-400">{new Date(row.createdAt).toLocaleTimeString('en-IN')}</td><td className="px-3 py-3 font-bold text-white">{row.symbol}</td><td className="px-3 py-3 text-slate-300">{row.message}</td><td className="px-3 py-3 text-cyan-300">{row.status}</td></tr>)}</tbody></table>{!center.data?.executionLog.length && <p className="py-10 text-center text-sm text-slate-500">No voice events recorded today.</p>}</div></div>
  </section></div>;
}
