ALTER TABLE "PaperTradingAccount" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'PAUSED';
ALTER TABLE "PaperTradingAccount" ADD COLUMN "executionState" TEXT NOT NULL DEFAULT 'WAITING';
ALTER TABLE "PaperTradingAccount" ADD COLUMN "stateReason" TEXT;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "maxDailyLossPercent" REAL NOT NULL DEFAULT 3;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "maxTradesPerDay" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "maxSectorExposure" REAL NOT NULL DEFAULT 100;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "cooldownAfterLossMinutes" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "cooldownAfterTradeMinutes" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "maximumHoldingMinutes" INTEGER NOT NULL DEFAULT 90;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "slippageBasisPoints" REAL NOT NULL DEFAULT 5;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "lastTradeClosedAt" DATETIME;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "lastLossAt" DATETIME;
ALTER TABLE "PaperTradingAccount" ADD COLUMN "reconciliationRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PaperOrder" ADD COLUMN "setupType" TEXT NOT NULL DEFAULT 'UNVERIFIED';
ALTER TABLE "PaperOrder" ADD COLUMN "exchange" TEXT NOT NULL DEFAULT 'NSE';
ALTER TABLE "PaperOrder" ADD COLUMN "signalTime" DATETIME;
ALTER TABLE "PaperOrder" ADD COLUMN "entrySignalPrice" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "slippage" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "target1" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "target2" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "initialStopLoss" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "riskAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "aiScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "calibratedProbability" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "historicalWinRate" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "historicalExpectancy" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "marketRegime" TEXT;
ALTER TABLE "PaperOrder" ADD COLUMN "sectorRegime" TEXT;
ALTER TABLE "PaperOrder" ADD COLUMN "riskReward" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "selectionReason" TEXT;
CREATE TABLE "DemoExecutionLease" ("userId" TEXT NOT NULL PRIMARY KEY, "acquiredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" DATETIME NOT NULL);
