ALTER TABLE "RealTradingAccount" ADD COLUMN "aggressiveMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AiSignal" ADD COLUMN "tradeQualityScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "tradeQualityRating" TEXT NOT NULL DEFAULT 'Skip';
ALTER TABLE "AiSignal" ADD COLUMN "qualityComponents" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "AiSignal" ADD COLUMN "idealEntryReady" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AiSignal" ADD COLUMN "idealEntryReason" TEXT NOT NULL DEFAULT 'Waiting for quality analysis';
ALTER TABLE "AiSignal" ADD COLUMN "target1Probability" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "target2Probability" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "target3Probability" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "expectedHoldingMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "expectedProfitPercent" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "expectedDrawdownPercent" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "qualityEvaluatedAt" DATETIME;
ALTER TABLE "RealTradeOrder" ADD COLUMN "tradeQualityScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "qualityRating" TEXT NOT NULL DEFAULT 'Skip';
ALTER TABLE "RealTradeOrder" ADD COLUMN "momentumScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "trendStrength" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "volumeScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "riskScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "targetProbability" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "expectedProfit" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "expectedHoldingMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "entryDelayMs" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "executionQuality" TEXT NOT NULL DEFAULT 'Unrated';
ALTER TABLE "RealTradeOrder" ADD COLUMN "marketCondition" TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE "RealTradeOrder" ADD COLUMN "sectorStrength" REAL NOT NULL DEFAULT 0;
ALTER TABLE "RealTradeOrder" ADD COLUMN "niftyTrend" TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE "RealTradeOrder" ADD COLUMN "bankNiftyTrend" TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE "RealTradeOrder" ADD COLUMN "brokerage" REAL;
ALTER TABLE "RealTradeOrder" ADD COLUMN "taxes" REAL;
ALTER TABLE "RealTradeOrder" ADD COLUMN "slippage" REAL;
ALTER TABLE "RealTradeOrder" ADD COLUMN "netProfit" REAL;
