-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_AiSignal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "signalKey" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "instrumentKey" TEXT NOT NULL,
    "stockName" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "sector" TEXT NOT NULL DEFAULT 'NSE Equity',
    "strategy" TEXT NOT NULL,
    "timeframe" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "signalTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "signalGeneratedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "currentPrice" REAL NOT NULL,
    "entryPrice" REAL NOT NULL,
    "stopLoss" REAL NOT NULL,
    "target1" REAL NOT NULL,
    "target2" REAL NOT NULL,
    "target3" REAL NOT NULL,
    "confidence" INTEGER NOT NULL,
    "aiScore" INTEGER NOT NULL,
    "riskReward" REAL NOT NULL,
    "volume" REAL NOT NULL DEFAULT 0,
    "universeRank" INTEGER NOT NULL DEFAULT 0,
    "selectionScore" REAL NOT NULL DEFAULT 0,
    "volumeRatio" REAL NOT NULL DEFAULT 0,
    "trendStrengthScore" REAL NOT NULL DEFAULT 0,
    "vwapAligned" BOOLEAN NOT NULL DEFAULT false,
    "emaAligned" BOOLEAN NOT NULL DEFAULT false,
    "momentumScore" REAL NOT NULL DEFAULT 0,
    "atrQuality" REAL NOT NULL DEFAULT 0,
    "finalTradingScore" REAL NOT NULL DEFAULT 0,
    "tradeQualityScore" REAL NOT NULL DEFAULT 0,
    "tradeQualityRating" TEXT NOT NULL DEFAULT 'Skip',
    "qualityComponents" TEXT NOT NULL DEFAULT '{}',
    "idealEntryReady" BOOLEAN NOT NULL DEFAULT false,
    "idealEntryReason" TEXT NOT NULL DEFAULT 'Waiting for quality analysis',
    "target1Probability" REAL NOT NULL DEFAULT 0,
    "target2Probability" REAL NOT NULL DEFAULT 0,
    "target3Probability" REAL NOT NULL DEFAULT 0,
    "expectedHoldingMinutes" INTEGER NOT NULL DEFAULT 0,
    "expectedProfitPercent" REAL NOT NULL DEFAULT 0,
    "expectedDrawdownPercent" REAL NOT NULL DEFAULT 0,
    "qualityEvaluatedAt" DATETIME,
    "entryRsi" REAL NOT NULL DEFAULT 0,
    "ema200Aligned" BOOLEAN NOT NULL DEFAULT false,
    "volumeIncreasing" BOOLEAN NOT NULL DEFAULT false,
    "marketTrendAligned" BOOLEAN NOT NULL DEFAULT false,
    "sectorStrength" REAL NOT NULL DEFAULT 0,
    "atr" REAL,
    "previousCandleLow" REAL,
    "previousCandleHigh" REAL,
    "top100Selected" BOOLEAN NOT NULL DEFAULT false,
    "setupFingerprint" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'WAITING',
    "entryTriggeredAt" DATETIME,
    "entryExecutedPrice" REAL,
    "runningAt" DATETIME,
    "target1At" DATETIME,
    "target1HitAt" DATETIME,
    "target1ExecutedPrice" REAL,
    "target2At" DATETIME,
    "target2HitAt" DATETIME,
    "target2ExecutedPrice" REAL,
    "target3At" DATETIME,
    "target3HitAt" DATETIME,
    "target3ExecutedPrice" REAL,
    "stopLossAt" DATETIME,
    "stopLossHitAt" DATETIME,
    "completedAt" DATETIME,
    "exitPrice" REAL,
    "profitPercent" REAL,
    "lossPercent" REAL,
    "holdingMinutes" INTEGER,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "AiSignal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_AiSignal" ("aiScore", "atr", "atrQuality", "completedAt", "confidence", "currentPrice", "ema200Aligned", "emaAligned", "entryExecutedPrice", "entryPrice", "entryRsi", "entryTriggeredAt", "exitPrice", "expectedDrawdownPercent", "expectedHoldingMinutes", "expectedProfitPercent", "finalTradingScore", "holdingMinutes", "id", "idealEntryReady", "idealEntryReason", "instrumentKey", "lossPercent", "marketTrendAligned", "momentumScore", "previousCandleHigh", "previousCandleLow", "profitPercent", "qualityComponents", "qualityEvaluatedAt", "riskReward", "runningAt", "sector", "sectorStrength", "selectionScore", "setupFingerprint", "side", "signalGeneratedAt", "signalKey", "signalTime", "status", "stockName", "stopLoss", "stopLossAt", "stopLossHitAt", "strategy", "symbol", "target1", "target1At", "target1ExecutedPrice", "target1HitAt", "target1Probability", "target2", "target2At", "target2ExecutedPrice", "target2HitAt", "target2Probability", "target3", "target3At", "target3ExecutedPrice", "target3HitAt", "target3Probability", "timeframe", "top100Selected", "tradeQualityRating", "tradeQualityScore", "trendStrengthScore", "universeRank", "updatedAt", "userId", "volume", "volumeIncreasing", "volumeRatio", "vwapAligned") SELECT "aiScore", "atr", "atrQuality", "completedAt", "confidence", "currentPrice", "ema200Aligned", "emaAligned", "entryExecutedPrice", "entryPrice", "entryRsi", "entryTriggeredAt", "exitPrice", "expectedDrawdownPercent", "expectedHoldingMinutes", "expectedProfitPercent", "finalTradingScore", "holdingMinutes", "id", "idealEntryReady", "idealEntryReason", "instrumentKey", "lossPercent", "marketTrendAligned", "momentumScore", "previousCandleHigh", "previousCandleLow", "profitPercent", "qualityComponents", "qualityEvaluatedAt", "riskReward", "runningAt", "sector", "sectorStrength", "selectionScore", "setupFingerprint", "side", coalesce("signalGeneratedAt", CURRENT_TIMESTAMP) AS "signalGeneratedAt", "signalKey", "signalTime", "status", "stockName", "stopLoss", "stopLossAt", "stopLossHitAt", "strategy", "symbol", "target1", "target1At", "target1ExecutedPrice", "target1HitAt", "target1Probability", "target2", "target2At", "target2ExecutedPrice", "target2HitAt", "target2Probability", "target3", "target3At", "target3ExecutedPrice", "target3HitAt", "target3Probability", "timeframe", "top100Selected", "tradeQualityRating", "tradeQualityScore", "trendStrengthScore", "universeRank", "updatedAt", "userId", "volume", "volumeIncreasing", "volumeRatio", "vwapAligned" FROM "AiSignal";
DROP TABLE "AiSignal";
ALTER TABLE "new_AiSignal" RENAME TO "AiSignal";
CREATE UNIQUE INDEX "AiSignal_signalKey_key" ON "AiSignal"("signalKey");
CREATE INDEX "AiSignal_userId_signalTime_idx" ON "AiSignal"("userId", "signalTime");
CREATE INDEX "AiSignal_userId_status_idx" ON "AiSignal"("userId", "status");
CREATE INDEX "AiSignal_instrumentKey_status_idx" ON "AiSignal"("instrumentKey", "status");
CREATE INDEX "AiSignal_userId_top100Selected_signalTime_idx" ON "AiSignal"("userId", "top100Selected", "signalTime");
CREATE TABLE "new_RealTradeOrder" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "signalId" TEXT NOT NULL,
    "brokerOrderId" TEXT,
    "instrumentKey" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "aiConfidence" REAL NOT NULL,
    "aiAnalysis" TEXT NOT NULL,
    "tradeQualityScore" REAL NOT NULL DEFAULT 0,
    "qualityRating" TEXT NOT NULL DEFAULT 'Skip',
    "momentumScore" REAL NOT NULL DEFAULT 0,
    "trendStrength" REAL NOT NULL DEFAULT 0,
    "volumeScore" REAL NOT NULL DEFAULT 0,
    "riskScore" REAL NOT NULL DEFAULT 0,
    "targetProbability" REAL NOT NULL DEFAULT 0,
    "expectedProfit" REAL NOT NULL DEFAULT 0,
    "expectedHoldingMinutes" INTEGER NOT NULL DEFAULT 0,
    "entryDelayMs" INTEGER NOT NULL DEFAULT 0,
    "executionQuality" TEXT NOT NULL DEFAULT 'Unrated',
    "marketCondition" TEXT NOT NULL DEFAULT 'Unknown',
    "sectorStrength" REAL NOT NULL DEFAULT 0,
    "niftyTrend" TEXT NOT NULL DEFAULT 'Unknown',
    "bankNiftyTrend" TEXT NOT NULL DEFAULT 'Unknown',
    "brokerage" REAL,
    "taxes" REAL,
    "slippage" REAL,
    "netProfit" REAL,
    "status" TEXT NOT NULL,
    "entryPrice" REAL NOT NULL,
    "currentPrice" REAL NOT NULL,
    "highestPrice" REAL,
    "lowestPrice" REAL,
    "maxDrawdown" REAL NOT NULL DEFAULT 0,
    "quantity" INTEGER NOT NULL,
    "remainingQuantity" INTEGER NOT NULL,
    "allocatedCapital" REAL NOT NULL,
    "investment" REAL NOT NULL,
    "target1" REAL NOT NULL,
    "target2" REAL NOT NULL,
    "target3" REAL NOT NULL,
    "stopLoss" REAL NOT NULL,
    "currentStop" REAL NOT NULL,
    "targetProgress" TEXT NOT NULL DEFAULT 'ENTRY',
    "target1ExitTime" DATETIME,
    "target1ExitPrice" REAL,
    "target2ExitTime" DATETIME,
    "target2ExitPrice" REAL,
    "realizedPnl" REAL NOT NULL DEFAULT 0,
    "pnl" REAL NOT NULL DEFAULT 0,
    "pnlPercent" REAL NOT NULL DEFAULT 0,
    "executionTime" DATETIME,
    "exitPrice" REAL,
    "exitReason" TEXT,
    "exitTime" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_RealTradeOrder" ("aiAnalysis", "aiConfidence", "allocatedCapital", "bankNiftyTrend", "brokerOrderId", "brokerage", "createdAt", "currentPrice", "currentStop", "entryDelayMs", "entryPrice", "executionQuality", "executionTime", "exitPrice", "exitReason", "exitTime", "expectedHoldingMinutes", "expectedProfit", "highestPrice", "id", "instrumentKey", "investment", "lowestPrice", "marketCondition", "maxDrawdown", "momentumScore", "netProfit", "niftyTrend", "pnl", "pnlPercent", "qualityRating", "quantity", "realizedPnl", "remainingQuantity", "riskScore", "sectorStrength", "side", "signalId", "slippage", "status", "stopLoss", "symbol", "target1", "target1ExitPrice", "target1ExitTime", "target2", "target2ExitPrice", "target2ExitTime", "target3", "targetProbability", "targetProgress", "taxes", "tradeQualityScore", "trendStrength", "updatedAt", "userId", "volumeScore") SELECT "aiAnalysis", "aiConfidence", "allocatedCapital", "bankNiftyTrend", "brokerOrderId", "brokerage", "createdAt", "currentPrice", "currentStop", "entryDelayMs", "entryPrice", "executionQuality", "executionTime", "exitPrice", "exitReason", "exitTime", "expectedHoldingMinutes", "expectedProfit", "highestPrice", "id", "instrumentKey", "investment", "lowestPrice", "marketCondition", "maxDrawdown", "momentumScore", "netProfit", "niftyTrend", "pnl", "pnlPercent", "qualityRating", "quantity", "realizedPnl", "remainingQuantity", "riskScore", "sectorStrength", "side", "signalId", "slippage", "status", "stopLoss", "symbol", "target1", "target1ExitPrice", "target1ExitTime", "target2", "target2ExitPrice", "target2ExitTime", "target3", "targetProbability", "targetProgress", "taxes", "tradeQualityScore", "trendStrength", "updatedAt", "userId", "volumeScore" FROM "RealTradeOrder";
DROP TABLE "RealTradeOrder";
ALTER TABLE "new_RealTradeOrder" RENAME TO "RealTradeOrder";
CREATE UNIQUE INDEX "RealTradeOrder_signalId_key" ON "RealTradeOrder"("signalId");
CREATE UNIQUE INDEX "RealTradeOrder_brokerOrderId_key" ON "RealTradeOrder"("brokerOrderId");
CREATE INDEX "RealTradeOrder_userId_status_idx" ON "RealTradeOrder"("userId", "status");
CREATE TABLE "new_RealTradeQueue" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "signalId" TEXT NOT NULL,
    "instrumentKey" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "entryPrice" REAL NOT NULL,
    "confidence" REAL NOT NULL,
    "aiScore" REAL NOT NULL,
    "riskReward" REAL NOT NULL,
    "rankScore" REAL NOT NULL DEFAULT 0,
    "volumeRatio" REAL NOT NULL DEFAULT 0,
    "trendStrength" REAL NOT NULL DEFAULT 0,
    "vwapAligned" BOOLEAN NOT NULL DEFAULT false,
    "emaAligned" BOOLEAN NOT NULL DEFAULT false,
    "momentum" REAL NOT NULL DEFAULT 0,
    "atrQuality" REAL NOT NULL DEFAULT 0,
    "entryMode" TEXT NOT NULL DEFAULT 'TARGET1_CONFIRMATION',
    "runningTime" DATETIME,
    "target1Reached" BOOLEAN NOT NULL DEFAULT false,
    "target1Time" DATETIME,
    "target1Price" REAL,
    "target1Momentum" REAL,
    "target1Volume" REAL,
    "target1VolumeIncreasing" BOOLEAN,
    "target1Vwap" REAL,
    "target1Ema20" REAL,
    "target1Ema50" REAL,
    "target1Rsi" REAL,
    "target1Macd" REAL,
    "target1Atr" REAL,
    "decisionResult" TEXT NOT NULL DEFAULT 'PENDING',
    "blockingCondition" TEXT,
    "signalTime" DATETIME NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'WAITING_FOR_SLOT',
    "displayStatus" TEXT NOT NULL DEFAULT 'Waiting',
    "validationLog" TEXT NOT NULL DEFAULT '[]',
    "brokerResponse" TEXT,
    "queuedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" DATETIME,
    "reason" TEXT,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_RealTradeQueue" ("aiScore", "atrQuality", "blockingCondition", "brokerResponse", "confidence", "decisionResult", "displayStatus", "emaAligned", "entryMode", "entryPrice", "id", "instrumentKey", "momentum", "queuedAt", "rankScore", "reason", "resolvedAt", "riskReward", "runningTime", "side", "signalId", "signalTime", "status", "symbol", "target1Atr", "target1Ema20", "target1Ema50", "target1Macd", "target1Momentum", "target1Price", "target1Reached", "target1Rsi", "target1Time", "target1Volume", "target1VolumeIncreasing", "target1Vwap", "trendStrength", "updatedAt", "userId", "validationLog", "volumeRatio", "vwapAligned") SELECT "aiScore", "atrQuality", "blockingCondition", "brokerResponse", "confidence", "decisionResult", "displayStatus", "emaAligned", "entryMode", "entryPrice", "id", "instrumentKey", "momentum", "queuedAt", "rankScore", "reason", "resolvedAt", "riskReward", "runningTime", "side", "signalId", "signalTime", "status", "symbol", "target1Atr", "target1Ema20", "target1Ema50", "target1Macd", "target1Momentum", "target1Price", "target1Reached", "target1Rsi", "target1Time", "target1Volume", "target1VolumeIncreasing", "target1Vwap", "trendStrength", "updatedAt", "userId", "validationLog", "volumeRatio", "vwapAligned" FROM "RealTradeQueue";
DROP TABLE "RealTradeQueue";
ALTER TABLE "new_RealTradeQueue" RENAME TO "RealTradeQueue";
CREATE UNIQUE INDEX "RealTradeQueue_signalId_key" ON "RealTradeQueue"("signalId");
CREATE INDEX "RealTradeQueue_userId_status_confidence_aiScore_idx" ON "RealTradeQueue"("userId", "status", "confidence", "aiScore");
CREATE TABLE "new_RealTradingAccount" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "tradingCapital" REAL NOT NULL DEFAULT 10000,
    "maxOpenTrades" INTEGER NOT NULL DEFAULT 5,
    "riskPerTrade" REAL NOT NULL DEFAULT 1,
    "minimumConfidence" REAL NOT NULL DEFAULT 75,
    "maxDailyLoss" REAL NOT NULL DEFAULT 1000,
    "maxDailyProfit" REAL NOT NULL DEFAULT 2000,
    "autoTrading" BOOLEAN NOT NULL DEFAULT false,
    "buySignals" BOOLEAN NOT NULL DEFAULT true,
    "sellSignals" BOOLEAN NOT NULL DEFAULT true,
    "squareOffTime" TEXT NOT NULL DEFAULT '15:15',
    "entryMode" TEXT NOT NULL DEFAULT 'IMMEDIATE_ENTRY',
    "aggressiveMode" BOOLEAN NOT NULL DEFAULT false,
    "connectionTime" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_RealTradingAccount" ("aggressiveMode", "autoTrading", "buySignals", "connectionTime", "createdAt", "entryMode", "id", "maxDailyLoss", "maxDailyProfit", "maxOpenTrades", "minimumConfidence", "riskPerTrade", "sellSignals", "squareOffTime", "tradingCapital", "updatedAt", "userId") SELECT "aggressiveMode", "autoTrading", "buySignals", "connectionTime", "createdAt", "entryMode", "id", "maxDailyLoss", "maxDailyProfit", "maxOpenTrades", "minimumConfidence", "riskPerTrade", "sellSignals", "squareOffTime", "tradingCapital", "updatedAt", "userId" FROM "RealTradingAccount";
DROP TABLE "RealTradingAccount";
ALTER TABLE "new_RealTradingAccount" RENAME TO "RealTradingAccount";
CREATE UNIQUE INDEX "RealTradingAccount_userId_key" ON "RealTradingAccount"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
