ALTER TABLE "PaperTradingAccount" ADD COLUMN "maximumHoldingMinutes" INTEGER NOT NULL DEFAULT 180;
ALTER TABLE "AiSignal" ADD COLUMN "finalTradingScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "entryRsi" REAL NOT NULL DEFAULT 0;
ALTER TABLE "AiSignal" ADD COLUMN "ema200Aligned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AiSignal" ADD COLUMN "volumeIncreasing" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AiSignal" ADD COLUMN "marketTrendAligned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AiSignal" ADD COLUMN "sectorStrength" REAL NOT NULL DEFAULT 0;
