ALTER TABLE "PaperOrder" ADD COLUMN "marketValue" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "unrealizedPnl" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "unrealizedPnlPercent" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PaperOrder" ADD COLUMN "target1" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "target2" REAL;
ALTER TABLE "PaperOrder" ADD COLUMN "tradeStage" TEXT NOT NULL DEFAULT 'RUNNING';
