import * as assert from 'node:assert/strict';
import { test } from 'node:test';
import { ExecutionEngine } from './execution-engine.service';
const engine=new ExecutionEngine(), now=new Date('2026-08-10T04:00:00.000Z');
const buy={side:'BUY',strategy:'ORB',signalTime:now,currentPrice:100,entryPrice:100,stopLoss:98,target1:103,target2:106,target3:109,confidence:94,aiScore:91,riskReward:3.2,volumeRatio:1.5,volumeIncreasing:true,marketTrendAligned:true,sectorStrength:70};
const context={now,marketOpen:true,availableCapital:10_000,tradingCapital:10_000,riskPercent:1,openTrades:0,maxOpenTrades:5,dailyLoss:0,maximumDailyLoss:1000,minimumConfidence:90,allowMedium:true};
test('valid BUY executes',()=>assert.equal(engine.decide(buy,context).action,'EXECUTE'));
test('valid SELL executes',()=>assert.equal(engine.decide({...buy,side:'SELL',stopLoss:102,target1:97,target2:94,target3:91},context).action,'EXECUTE'));
test('temporarily low confidence revalidates',()=>assert.equal(engine.decide({...buy,confidence:89},context).action,'REVALIDATE'));
test('small valid price movement executes',()=>assert.equal(engine.decide({...buy,currentPrice:100.2},context).action,'EXECUTE'));
test('larger price movement recalculates',()=>assert.equal(engine.decide({...buy,currentPrice:100.31},context).action,'RECALCULATE'));
test('partial capital calculates affordable quantity',()=>assert.equal(engine.decide(buy,{...context,availableCapital:150}).quantity,1));
test('duplicate position is blocked',()=>assert.equal(engine.decide(buy,{...context,duplicatePosition:true}).hardBlocker,'Duplicate position'));
test('target 1 advances without closing',()=>assert.deepEqual(engine.exitDecision('BUY',103,98,103,106,109),{state:'TARGET_1',close:false,reason:'TARGET_1'}));
test('target 2 advances without closing',()=>assert.deepEqual(engine.exitDecision('BUY',106,98,103,106,109,'TARGET_1'),{state:'TARGET_2',close:false,reason:'TARGET_2'}));
test('target 3 closes',()=>assert.equal(engine.exitDecision('BUY',109,98,103,106,109,'TARGET_2').close,true));
test('stop loss closes',()=>assert.equal(engine.exitDecision('BUY',98,98,103,106,109).reason,'STOP_LOSS'));
test('market closed is blocked',()=>assert.equal(engine.decide(buy,{...context,marketOpen:false}).hardBlocker,'Market closed'));
test('daily loss limit blocks entries',()=>assert.equal(engine.decide(buy,{...context,dailyLoss:1000}).hardBlocker,'Daily loss limit reached'));
test('stale signal is revalidated or recalculated, not expired',()=>assert.equal(engine.decide({...buy,signalTime:new Date(now.getTime()-35_000)},context).action,'RECALCULATE'));
test('completed trade cannot run again',()=>assert.equal(engine.canTransition('COMPLETED','RUNNING'),false));
test('temporary execution failure retries and creates exactly one result',async()=>{let calls=0;const operation=async()=>{calls++;if(calls<2)throw new Error('temporary');return{id:'one'};};const first=await engine.executeWithRetry('execution-1',operation);const second=await engine.executeWithRetry('execution-1',operation);assert.deepEqual(first,second);assert.equal(calls,2);});
