import { Injectable } from '@nestjs/common';
import { UpstoxService } from './upstox.service';
export const TRADING_PRODUCT='I' as const, TRADING_PRODUCT_TYPE='INTRADAY' as const, CAPITAL_BUFFER_PERCENT=5;
export type IntradayQuantityInput={userId:string;capital:number;symbol:string;instrumentKey:string;entryPrice:number;stopLoss:number;target1:number;side:'BUY'|'SELL';riskPerTrade:number;maxOpenTrades:number;configuredMaximumQuantity?:number;capitalBufferPercent?:number};
@Injectable()
export class IntradayExecutionService {
 constructor(private readonly upstox:UpstoxService){}
 async calculateIntradayQuantity(i:IntradayQuantityInput){
  const capital=Math.max(0,Number(i.capital)),bufferPercent=Math.max(0,Math.min(50,i.capitalBufferPercent??CAPITAL_BUFFER_PERCENT)),reservedCapital=capital*bufferPercent/100,usableCapital=capital-reservedCapital,riskPerShare=Math.abs(i.entryPrice-i.stopLoss),maximumRisk=capital*Math.max(0,i.riskPerTrade)/100,riskBasedQuantity=riskPerShare>0?Math.floor(maximumRisk/riskPerShare):0,configuredMaximumQuantity=Math.max(1,Math.floor(i.configuredMaximumQuantity??100_000)),upper=Math.min(riskBasedQuantity,configuredMaximumQuantity);
  if(!(usableCapital>0)||!(upper>0))return this.empty(i,capital,reservedCapital,usableCapital,riskPerShare,maximumRisk,riskBasedQuantity,'Risk or usable capital permits zero quantity');
  let low=1,high=upper,marginBasedQuantity=0,requiredIntradayMargin=0;
  while(low<=high){const middle=Math.floor((low+high)/2),margin=await this.upstox.intradayMargin(i.userId,{instrumentKey:i.instrumentKey,quantity:middle,side:i.side,price:i.entryPrice});if(margin<=usableCapital){marginBasedQuantity=middle;requiredIntradayMargin=margin;low=middle+1;}else high=middle-1;}
  const finalQuantity=Math.min(marginBasedQuantity,riskBasedQuantity,configuredMaximumQuantity);if(finalQuantity<=0)return this.empty(i,capital,reservedCapital,usableCapital,riskPerShare,maximumRisk,riskBasedQuantity,'Intraday margin permits zero quantity');if(finalQuantity!==marginBasedQuantity)requiredIntradayMargin=await this.upstox.intradayMargin(i.userId,{instrumentKey:i.instrumentKey,quantity:finalQuantity,side:i.side,price:i.entryPrice});
  const marginPerShare=requiredIntradayMargin/finalQuantity,expectedGrossProfit=Math.abs(i.target1-i.entryPrice)*finalQuantity,charges=await this.estimateRoundTripCharges(i.userId,i.instrumentKey,i.side,finalQuantity,i.entryPrice,i.target1),estimatedCharges=charges.total,expectedNetProfit=expectedGrossProfit-estimatedCharges,viable=expectedNetProfit>0;
  return{product:TRADING_PRODUCT,productType:TRADING_PRODUCT_TYPE,capital,reservedCapital,usableCapital,marginPerShare,marginBasedQuantity,riskPerShare,maximumRisk,riskBasedQuantity,configuredMaximumQuantity,finalQuantity,requiredIntradayMargin,notionalValue:i.entryPrice*finalQuantity,expectedGrossProfit,estimatedCharges,expectedNetProfit,chargeBreakdown:charges,viable,reason:viable?'Economically viable intraday trade':finalQuantity===1?'Quantity 1 is not economically viable after charges.':'Trade not economically viable after estimated charges.'};
 }
 async getMarginProfile(userId:string,instrumentKey:string,side:'BUY'|'SELL',entryPrice:number){const marginPerShare=await this.upstox.intradayMargin(userId,{instrumentKey,quantity:1,side,price:entryPrice});return{intradayMargin:entryPrice>0?marginPerShare/entryPrice*100:null,intradayLeverage:marginPerShare>0?entryPrice/marginPerShare:null};}
 async estimateRoundTripCharges(userId:string,instrumentKey:string,entrySide:'BUY'|'SELL',quantity:number,entryPrice:number,exitPrice:number){const exitSide=entrySide==='BUY'?'SELL':'BUY';const[entry,exit]=await Promise.all([this.upstox.brokerageCharges(userId,{instrumentKey,quantity,side:entrySide,price:entryPrice}),this.upstox.brokerageCharges(userId,{instrumentKey,quantity,side:exitSide,price:exitPrice})]);return{total:entry.total+exit.total,entry,exit};}
 private empty(i:IntradayQuantityInput,capital:number,reservedCapital:number,usableCapital:number,riskPerShare:number,maximumRisk:number,riskBasedQuantity:number,reason:string){return{product:TRADING_PRODUCT,productType:TRADING_PRODUCT_TYPE,capital,reservedCapital,usableCapital,marginPerShare:0,marginBasedQuantity:0,riskPerShare,maximumRisk,riskBasedQuantity,configuredMaximumQuantity:i.configuredMaximumQuantity??100_000,finalQuantity:0,requiredIntradayMargin:0,notionalValue:0,expectedGrossProfit:0,estimatedCharges:0,expectedNetProfit:0,chargeBreakdown:null,viable:false,reason};}
}
