import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { NiftyDemoService } from './nifty-demo.service';
import { PaperOrderExecutionService } from './paper-order-execution.service';
import { PrismaService } from '../prisma.service';
import { MarketGateway } from './market.gateway';
import { defaults, NIFTY_KEY } from './nifty-engine';
test('option demo persists canonical orders, blocks duplicates and stale data, settles CE and PE premium P&L', async () => {
  const dir = mkdtempSync(join(tmpdir(),'nifty-demo-'));
  const db = new PrismaClient({datasources:{db:{url:`file:${join(dir,'test.db')}`}}});
  let service: NiftyDemoService | undefined;
  try {
    const sql=execFileSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','diff','--from-empty','--to-schema-datamodel',join(__dirname,'../../prisma/schema.prisma'),'--script'],{encoding:'utf8'});
    for(const statement of sql.split(';').map(s=>s.trim()).filter(Boolean))await db.$executeRawUnsafe(statement);
    await db.$executeRawUnsafe(`CREATE UNIQUE INDEX "PaperOrder_nifty_one_open" ON "PaperOrder"("userId") WHERE "portfolio" = 'NIFTY' AND "status" = 'OPEN'`);
    const user=await db.user.create({data:{upstoxUserId:'option-demo'}});
    let price=100,stamp=Date.now(),trusted=true;
    const events:string[]=[];
    const feed={onPrice:()=>()=>undefined,subscribe:async()=>undefined,latestUserSnapshot:(_u:string,key:string)=>({ltp:key===NIFTY_KEY?22000:price,timestamp:stamp,timestampTrusted:trusted}),latestOptionBook:()=>({ltp:price,bid:price-.5,ask:price,volume:5000}),emitToUser:(_u:string,_e:string,p:{type:string})=>events.push(p.type)};
    service=new NiftyDemoService(db as PrismaService,feed as unknown as MarketGateway,new PaperOrderExecutionService());
    const settings={...defaults,riskPercent:5,dailyLossPercent:10,optionStopPercent:10,optionTargetR:3,cutoff:'23:58',squareOff:'23:59',maxConsecutiveLosses:3};
    const contract={instrumentKey:'NSE_FO|CE',symbol:'NIFTY CE',lotSize:10,expiry:'2026-09-24',strike:22000,type:'CE'};
    let sequence=0;
    async function signal(side:string) {return db.aiSignal.create({data:{signalKey:`demo-${side}-${sequence++}`,userId:user.id,instrumentKey:NIFTY_KEY,stockName:'NIFTY',symbol:'NIFTY',sector:'NSE',strategy:'TREND_PULLBACK',timeframe:'15m/5m/3m',side,signalTime:new Date(),currentPrice:22000,entryPrice:22000,stopLoss:side==='BUY'?21900:22100,target1:22100,target2:22200,target3:22300,status:'WAITING',confidence:90,aiScore:90,riskReward:3,volume:1000,niftyContext:{create:{setupId:`demo-${side}-${sequence}`,inputs:'{}',optionContract:JSON.stringify(contract),reasons:'["3M confirmed"]',invalidations:'["Structural stop"]',setupDetectedAt:new Date()}}}});}
    const ce=await signal('BUY');
    await service.enter(user.id,ce.id,contract,settings);assert.equal(await db.paperOrder.count(),0);
    await db.aiSignal.update({where:{id:ce.id},data:{aiScore:60}});
    await service.enter(user.id,ce.id,contract,settings,true);assert.equal(await db.paperOrder.count(),0);
    await db.aiSignal.update({where:{id:ce.id},data:{aiScore:90}});
    trusted=false;await service.enter(user.id,ce.id,contract,settings,true);assert.equal(await db.paperOrder.count(),0);
    trusted=true;stamp=Date.now()-settings.staleMs-1;await service.enter(user.id,ce.id,contract,settings,true);assert.equal(await db.paperOrder.count(),0);
    stamp=Date.now();await service.enter(user.id,ce.id,contract,settings,true);await service.enter(user.id,ce.id,contract,settings,true);
    assert.equal(await db.paperOrder.count(),1);const order=await db.paperOrder.findUniqueOrThrow({where:{id:ce.id}});assert.equal(order.entryPrice,100);assert.equal(order.quantity%contract.lotSize,0);
    const pe=await signal('SELL');await service.enter(user.id,pe.id,{...contract,type:'PE'},settings,true);assert.equal(await db.paperOrder.count(),1);
    await assert.rejects(db.paperOrder.create({data:{...order,id:'conflict',signalId:null}}));
    const update=service as unknown as {update:(user:string,key:string)=>Promise<void>};
    price=110;stamp=Date.now()+1;await update.update(user.id,contract.instrumentKey);
    assert.ok(events.includes('T1_hit'));assert.equal((await db.paperOrder.findUniqueOrThrow({where:{id:ce.id}})).pnl,10*order.quantity);
    price=130;stamp+=1;await update.update(user.id,contract.instrumentKey);
    const closed=await db.paperOrder.findUniqueOrThrow({where:{id:ce.id}});assert.equal(closed.status,'CLOSED');assert.equal(closed.pnl,30*order.quantity);
    await update.update(user.id,contract.instrumentKey);assert.equal((await service.view(user.id)).realizedPnl,closed.pnl);
    price=100;stamp+=1;await service.enter(user.id,pe.id,{...contract,type:'PE'},settings,true);
    const put=await db.paperOrder.findUniqueOrThrow({where:{id:pe.id}});price=90;stamp+=1;await update.update(user.id,contract.instrumentKey);
    assert.equal((await db.paperOrder.findUniqueOrThrow({where:{id:pe.id}})).pnl,-10*put.quantity);
    assert.equal((await service.view(user.id)).realizedPnl,closed.pnl-10*put.quantity);
    const next=await signal('BUY');price=100;stamp+=1;
    await service.enter(user.id,next.id,contract,{...settings,maxTrades:2},true);assert.equal(await db.paperOrder.count(),2);
    await service.enter(user.id,next.id,contract,{...settings,maxConsecutiveLosses:1},true);assert.equal(await db.paperOrder.count(),2);
    await service.enter(user.id,next.id,contract,{...settings,riskPercent:.0001},true);assert.equal(await db.paperOrder.count(),2);
    await service.enter(user.id,next.id,contract,settings,true);
    const finalOrder=await db.paperOrder.findUniqueOrThrow({where:{id:next.id}});
    const metadata=JSON.parse(finalOrder.niftyDemo!);metadata.settings.squareOff='00:00';
    await db.paperOrder.update({where:{id:next.id},data:{niftyDemo:JSON.stringify(metadata)}});
    trusted=false;await service.heartbeat();assert.equal((await db.paperOrder.findUniqueOrThrow({where:{id:next.id}})).status,'OPEN');
    trusted=true;stamp=Date.now();await service.heartbeat();assert.equal((await db.paperOrder.findUniqueOrThrow({where:{id:next.id}})).exitReason,'AUTO EXIT');
    assert.equal(await db.aiTradeEvent.count({where:{tradeId:next.id,type:'DEMO_CLOSED'}}),1);
    const migration=readFileSync(join(__dirname,'../../prisma/migrations/202609170001_nifty_demo/migration.sql'),'utf8');assert.ok(migration.includes("WHERE \"portfolio\" = 'NIFTY'"));
  } finally {service?.onModuleDestroy();await db.$disconnect();rmSync(dir,{recursive:true,force:true});}
});
